### PR TITLE
Add Trezarcoin (TZC)

### PR DESCRIPTION
**Pull request by Bushstar**

### CODE REVIEW

**Comment by martinboehm** [comment]
Hi, I checked your PR. All looks functional except for the integration tests. I got errors like:
```
=== RUN   TestIntegration/trezarcoin=main/rpc/GetTransaction
    TestIntegration/trezarcoin=main/rpc/GetTransaction: rpc.go:185: GetTransaction()
got  &bchain.Tx{Hex:"01000000fdc4745e010000000000000000000000000000000000000000000000000000000000000000ffffffff1f03f4e41304c9c4745e08810078cef13400007a657267706f6f6c2e636f6d00000000000100e1f505000000002321036842117fa1b85649c3e2e84c759387d5670051213c61764e2a5bbf55260c2f3bac00000000", Txid:"c35f4d078ec352096c1f83908f87e4fbb9553f264b0ba139cd7ca82dc060105a", Version:1, LockTime:0x0, Vin:[]bchain.Vin{bchain.Vin{Coinbase:"03f4e41304c9c4745e08810078cef13400007a657267706f6f6c2e636f6d00", Txid:"", Vout:0x0, ScriptSig:bchain.ScriptSig{Hex:""}, Sequence:0x0, Addresses:[]string(nil)}}, Vout:[]bchain.Vout{bchain.Vout{ValueSat:big.Int{neg:false, abs:big.nat{0x2540be400}}, JsonValue:"", N:0x0, ScriptPubKey:bchain.ScriptPubKey{Hex:"21036842117fa1b85649c3e2e84c759387d5670051213c61764e2a5bbf55260c2f3bac", Addresses:[]string{"TeiQt4soequkxza72oisyVnStKD6xeo4EL"}}}}, BlockHeight:0x0, Confirmations:0x0, Time:1584710909, Blocktime:1584710909, CoinSpecificData:interface {}(nil)},
want &bchain.Tx{Hex:"01000000fdc4745e010000000000000000000000000000000000000000000000000000000000000000ffffffff1f03f4e41304c9c4745e08810078cef13400007a657267706f6f6c2e636f6d00000000000100e1f505000000002321036842117fa1b85649c3e2e84c759387d5670051213c61764e2a5bbf55260c2f3bac00000000", Txid:"c35f4d078ec352096c1f83908f87e4fbb9553f264b0ba139cd7ca82dc060105a", Version:1, LockTime:0x0, Vin:[]bchain.Vin{bchain.Vin{Coinbase:"03f4e41304c9c4745e08810078cef13400007a657267706f6f6c2e636f6d00", Txid:"", Vout:0x0, ScriptSig:bchain.ScriptSig{Hex:""}, Sequence:0x0, Addresses:[]string(nil)}}, Vout:[]bchain.Vout{bchain.Vout{ValueSat:big.Int{neg:false, abs:big.nat{0x2540be400}}, JsonValue:"", N:0x0, ScriptPubKey:bchain.ScriptPubKey{Hex:"76a9143b4f5324853e05e8d5f8378eeea167c6fb627c7388ac", Addresses:[]string{"TeiQt4soequkxza72oisyVnStKD6xeo4EL"}}}}, BlockHeight:0x0, Confirmations:0x0, Time:1584710909, Blocktime:1584710909, CoinSpecificData:interface {}(nil)}
```

**Comment by Bushstar** [comment]
@martinboehm Thanks for letting us know. I'll look into this and will update the PR.

**Comment by Bushstar** [comment]
@martinboehm apologies for the long delay. The PR has been updated and should now work, please run the tests again.

Quick question, when I try to manually run the integration tests I get the message.

`?   	github.com/trezor/blockbook	[no test files]`

I'm trying to run the tests for TrezarCoin as follows.

`make test-integration ARGS="-run=TestIntegration/trezarcoin/"`

How did you get the integration test that failed to run?

**Comment by martinboehm** [comment]
I used `make test-integration ARGS="-v -run=TestIntegration/trezarcoin=main"` for the integration test.

**Comment by Bushstar** [comment]
> I used `make test-integration ARGS="-v -run=TestIntegration/trezarcoin=main"` for the integration test.

I'm not getting any errors with the updated PR.

**Pull request merged**
