### PR TITLE
Add VIPSTARCOIN

### PR DESCRIPTION
**Pull request by y-chan**
Hi, I'm added VIPSTARCOIN for blockbook.
I have running blockbook for VIPSTARCOIN.
[here](https://vips.blockbook.japanesecoin-pool.work)

### CODE REVIEW

**Comment by martinboehm** [comment]
Hi, thanks for your contribution. 
Could you please use ports xx56 instead of xx90?

**Comment by y-chan** [comment]
Ok, fix it.

**Comment by martinboehm** [comment]
Hi, I got integration test failure, running the following command:
`
make test-integration ARGS="-v -run=TestIntegration/vipstarcoin=main"
`
```
    --- FAIL: TestIntegration/vipstarcoin=main (2.45s)
        --- FAIL: TestIntegration/vipstarcoin=main/rpc (0.04s)
            --- FAIL: TestIntegration/vipstarcoin=main/rpc/EstimateSmartFee (0.01s)
                rpc.go:245: -1: estimatesmartfee nblocks
				...
        --- FAIL: TestIntegration/vipstarcoin=main/sync (2.28s)
            --- FAIL: TestIntegration/vipstarcoin=main/sync/HandleFork (0.22s)
                handlefork.go:151: VT3nFv2cZjG19exJhQegfG2wt3KTXRpD8D: transaction fcce09ee27147912b737c080e463ac3cfa1d3d1c35cf2eb5430b10ac8fa15d13 was found [expected = false]
                handlefork.go:151: VT3nFv2cZjG19exJhQegfG2wt3KTXRpD8D: transaction fcce09ee27147912b737c080e463ac3cfa1d3d1c35cf2eb5430b10ac8fa15d13 was found [expected = false]
```

**Comment by y-chan** [comment]
Thanks!

**Pull request merged**
