### PR TITLE
added OmotenashiCoin(MTNS)

### PR DESCRIPTION
**Pull request by omotenashicoin-project**
Please add OmotenashiCoin to your blockbook.

Our web site here : http://www.omotenashicoin.site/
I added source code and test code.

====
Test results:
$ make test

Image blockbook-build is up to date
docker run -t --rm -e PACKAGER=1000:1000 -e UPDATE_VENDOR=1 -v /home/ubuntu/hardwallet/blockbook-mtns-new:/src --network="host" blockbook-build make test ARGS=""
rm -rf /go/src/blockbook
cp -r /src /go/src/blockbook
make prepare-vendor
make[1]: Entering directory '/build'
Updating vendor
make[1]: Leaving directory '/build'
cd /go/src/blockbook && packr clean && packr
cd /go/src/blockbook && go test -tags unittest `go list ./... | grep -vP '^blockbook/(contrib|tests)'`

ok      blockbook/bchain/coins/omotenashicoin   0.160s

$ make test-integration ARGS="-v -run=TestIntegration/omotenashicoin/"
Image blockbook-build is up to date
docker run -t --rm -e PACKAGER=1000:1000 -e UPDATE_VENDOR=1 -v /home/ubuntu/hardwallet/blockbook-mtns-new:/src --network="host" blockbook-build make test-integration ARGS="-v -run=TestIntegration/omotenashicoin/"
rm -rf /go/src/blockbook
cp -r /src /go/src/blockbook
make prepare-vendor
make[1]: Entering directory '/build'
Updating vendor
make[1]: Leaving directory '/build'
cd /go/src/blockbook && packr clean && packr
cd /go/src/blockbook && go test -tags integration `go list blockbook/tests/...` -v -run=TestIntegration/omotenashicoin/
=== RUN   TestIntegration
=== RUN   TestIntegration/omotenashicoin=main
=== RUN   TestIntegration/omotenashicoin=main/rpc
=== RUN   TestIntegration/omotenashicoin=main/rpc/GetBlock
=== RUN   TestIntegration/omotenashicoin=main/rpc/GetBlockHash
=== RUN   TestIntegration/omotenashicoin=main/rpc/GetTransaction
=== RUN   TestIntegration/omotenashicoin=main/rpc/GetTransactionForMempool
=== RUN   TestIntegration/omotenashicoin=main/rpc/MempoolSync
=== RUN   TestIntegration/omotenashicoin=main/rpc/EstimateSmartFee
=== RUN   TestIntegration/omotenashicoin=main/rpc/EstimateFee
=== RUN   TestIntegration/omotenashicoin=main/rpc/GetBestBlockHash
=== RUN   TestIntegration/omotenashicoin=main/rpc/GetBestBlockHeight
=== RUN   TestIntegration/omotenashicoin=main/sync
=== RUN   TestIntegration/omotenashicoin=main/sync/ConnectBlocksParallel
=== RUN   TestIntegration/omotenashicoin=main/sync/ConnectBlocksParallel/verifyBlockInfo
=== RUN   TestIntegration/omotenashicoin=main/sync/ConnectBlocksParallel/verifyTransactions
=== RUN   TestIntegration/omotenashicoin=main/sync/ConnectBlocksParallel/verifyAddresses
=== RUN   TestIntegration/omotenashicoin=main/sync/ConnectBlocks
=== RUN   TestIntegration/omotenashicoin=main/sync/ConnectBlocks/verifyBlockInfo
=== RUN   TestIntegration/omotenashicoin=main/sync/ConnectBlocks/verifyTransactions
=== RUN   TestIntegration/omotenashicoin=main/sync/ConnectBlocks/verifyAddresses
=== RUN   TestIntegration/omotenashicoin=test
=== RUN   TestIntegration/omotenashicoin=test/rpc
=== RUN   TestIntegration/omotenashicoin=test/rpc/GetBlock
=== RUN   TestIntegration/omotenashicoin=test/rpc/GetBlockHash
=== RUN   TestIntegration/omotenashicoin=test/rpc/GetTransaction
=== RUN   TestIntegration/omotenashicoin=test/rpc/GetTransactionForMempool
=== RUN   TestIntegration/omotenashicoin=test/rpc/MempoolSync
=== RUN   TestIntegration/omotenashicoin=test/rpc/EstimateSmartFee
=== RUN   TestIntegration/omotenashicoin=test/rpc/EstimateFee
=== RUN   TestIntegration/omotenashicoin=test/rpc/GetBestBlockHash
=== RUN   TestIntegration/omotenashicoin=test/rpc/GetBestBlockHeight
=== RUN   TestIntegration/omotenashicoin=test/sync
=== RUN   TestIntegration/omotenashicoin=test/sync/ConnectBlocksParallel
=== RUN   TestIntegration/omotenashicoin=test/sync/ConnectBlocksParallel/verifyBlockInfo
=== RUN   TestIntegration/omotenashicoin=test/sync/ConnectBlocksParallel/verifyTransactions
=== RUN   TestIntegration/omotenashicoin=test/sync/ConnectBlocksParallel/verifyAddresses
=== RUN   TestIntegration/omotenashicoin=test/sync/ConnectBlocks
=== RUN   TestIntegration/omotenashicoin=test/sync/ConnectBlocks/verifyBlockInfo
=== RUN   TestIntegration/omotenashicoin=test/sync/ConnectBlocks/verifyTransactions
=== RUN   TestIntegration/omotenashicoin=test/sync/ConnectBlocks/verifyAddresses
--- PASS: TestIntegration (0.50s)
    --- PASS: TestIntegration/omotenashicoin=main (0.25s)
        --- PASS: TestIntegration/omotenashicoin=main/rpc (0.01s)
            --- PASS: TestIntegration/omotenashicoin=main/rpc/GetBlock (0.00s)
            --- PASS: TestIntegration/omotenashicoin=main/rpc/GetBlockHash (0.00s)
            --- PASS: TestIntegration/omotenashicoin=main/rpc/GetTransaction (0.00s)
            --- PASS: TestIntegration/omotenashicoin=main/rpc/GetTransactionForMempool (0.00s)
            --- SKIP: TestIntegration/omotenashicoin=main/rpc/MempoolSync (0.00s)
                rpc.go:394: Skipping test, mempool is empty
            --- PASS: TestIntegration/omotenashicoin=main/rpc/EstimateSmartFee (0.00s)
            --- PASS: TestIntegration/omotenashicoin=main/rpc/EstimateFee (0.00s)
            --- PASS: TestIntegration/omotenashicoin=main/rpc/GetBestBlockHash (0.00s)
            --- PASS: TestIntegration/omotenashicoin=main/rpc/GetBestBlockHeight (0.00s)
        --- PASS: TestIntegration/omotenashicoin=main/sync (0.23s)
            --- PASS: TestIntegration/omotenashicoin=main/sync/ConnectBlocksParallel (0.12s)
                --- PASS: TestIntegration/omotenashicoin=main/sync/ConnectBlocksParallel/verifyBlockInfo (0.00s)
                --- PASS: TestIntegration/omotenashicoin=main/sync/ConnectBlocksParallel/verifyTransactions (0.00s)
                --- PASS: TestIntegration/omotenashicoin=main/sync/ConnectBlocksParallel/verifyAddresses (0.00s)
            --- PASS: TestIntegration/omotenashicoin=main/sync/ConnectBlocks (0.11s)
                --- PASS: TestIntegration/omotenashicoin=main/sync/ConnectBlocks/verifyBlockInfo (0.00s)
                --- PASS: TestIntegration/omotenashicoin=main/sync/ConnectBlocks/verifyTransactions (0.00s)
                --- PASS: TestIntegration/omotenashicoin=main/sync/ConnectBlocks/verifyAddresses (0.00s)
    --- PASS: TestIntegration/omotenashicoin=test (0.25s)
        --- PASS: TestIntegration/omotenashicoin=test/rpc (0.01s)
            --- PASS: TestIntegration/omotenashicoin=test/rpc/GetBlock (0.00s)
            --- PASS: TestIntegration/omotenashicoin=test/rpc/GetBlockHash (0.00s)
            --- PASS: TestIntegration/omotenashicoin=test/rpc/GetTransaction (0.00s)
            --- PASS: TestIntegration/omotenashicoin=test/rpc/GetTransactionForMempool (0.00s)
            --- SKIP: TestIntegration/omotenashicoin=test/rpc/MempoolSync (0.00s)
                rpc.go:394: Skipping test, mempool is empty
            --- PASS: TestIntegration/omotenashicoin=test/rpc/EstimateSmartFee (0.00s)
            --- PASS: TestIntegration/omotenashicoin=test/rpc/EstimateFee (0.00s)
            --- PASS: TestIntegration/omotenashicoin=test/rpc/GetBestBlockHash (0.00s)
            --- PASS: TestIntegration/omotenashicoin=test/rpc/GetBestBlockHeight (0.00s)
        --- PASS: TestIntegration/omotenashicoin=test/sync (0.22s)
            --- PASS: TestIntegration/omotenashicoin=test/sync/ConnectBlocksParallel (0.11s)
                --- PASS: TestIntegration/omotenashicoin=test/sync/ConnectBlocksParallel/verifyBlockInfo (0.00s)
                --- PASS: TestIntegration/omotenashicoin=test/sync/ConnectBlocksParallel/verifyTransactions (0.00s)
                --- PASS: TestIntegration/omotenashicoin=test/sync/ConnectBlocksParallel/verifyAddresses (0.00s)
            --- PASS: TestIntegration/omotenashicoin=test/sync/ConnectBlocks (0.11s)
                --- PASS: TestIntegration/omotenashicoin=test/sync/ConnectBlocks/verifyBlockInfo (0.00s)
                --- PASS: TestIntegration/omotenashicoin=test/sync/ConnectBlocks/verifyTransactions (0.00s)
                --- PASS: TestIntegration/omotenashicoin=test/sync/ConnectBlocks/verifyAddresses (0.00s)
PASS
ok      blockbook/tests 0.697s

====
Thank you for considering our request.
We look forward to your response.

### CODE REVIEW

**Comment by martinboehm** [comment]
Hi, I am trying to sync the blockbook to backend, unfortunately I get

**Comment by omotenashicoin-project** [comment]
Hello, Admin.

Testing of our Trezor wallet client (Lightweight Omotenashicoin client) has already been completed on the mainnet.
Trezor firmware has already been merged, so please consider merging blockbooks.

Lightweight Omotenashicoin client URL:
https://github.com/omotenashicoin-project/OmotenashiCoin-HDwalletbinaries/tree/master/stable
Linux
electrum-mtns-3.3.9-x86_64.AppImage
Windows
electrum-mtns-3.3.9.exe

Trezor firmware source code merged PR ID:
https://github.com/trezor/trezor-firmware/pull/415

Blockbook web page:
mainnet-
https://mtns.chainview.site/
testnet-
https://mtnstestnet.chainview.site/

**Comment by martinboehm** [comment]
Hi sorry for the delay. We want to first merge an important fix (in the branch https://github.com/trezor/blockbook/tree/utxocheck), before merging any other pull request. It will be done soon.

**Comment by omotenashicoin-project** [comment]
Hello, martinboehm.

OK, Thanks for putting up with me.

**Comment by omotenashicoin-project** [comment]
Hello, Martin.


I was late replying to you.

Backend not syncing?

I will check the operation in my repository.

**Comment by martinboehm** [comment]
I think it may have been caused by a problem on our side. Let me retest it when I merge the https://github.com/trezor/blockbook/tree/utxocheck branch.

**Comment by omotenashicoin-project** [comment]
That makes sense.
When the code is updated by you, I will build and check again.

**Comment by martinboehm** [comment]
It is merged but github for some reason did not close the PR.

**Comment by omotenashicoin-project** [comment]
Hello, martinboehm.
I have confirmed that the code has been merged by you.
Thank you very much for your kind consideration.

**Pull request closed without merging**
