### PR TITLE
Viacoin add support

### PR DESCRIPTION
**Pull request by romanornr**
Blockbook running: http://95.179.129.179/blocks

Seems to be an issue tho.
Timestamp keeps showing ```Thu, 01 Jan 1970 00:00:00 UTC``` for all blocks. 

I'm not sure what I did wrong. Or this is just a problem in blockbook self.

### CODE REVIEW

**Comment by martinboehm** [comment]
In the `func (p *ViacoinParser) ParseBlock` you are parsing the header but you are not returning any data from it: `return &bchain.Block{Txs: txs}, nil`

**Comment by romanornr** [comment]
I see. Missed that. 
Just fixed and force pushed.

Now I will try to fix the public blockbook node I have running.

**Comment by romanornr** [comment]
It's syncing, public blockbook server can be viewed here: https://blockbook.viacoin.org

**Comment by romanornr** [comment]
Viacoin blockbook is synced.
https://blockbook.viacoin.org/

Hope it can be merged soon.

**Comment by martinboehm** [comment]
I tried to install and test it, however I get a port conflict with other coins installed on my server. Could you please specify the following ports in the config json:

```
    "backend_rpc": 8055,
    "backend_message_queue": 38355,
    "blockbook_internal": 9055,
    "blockbook_public": 9155
```

**Comment by romanornr** [comment]
Oke, I just force pushed the changes.

**Comment by martinboehm** [comment]
Hi, I was able to install and run backend and blockbook successfully. However, the integration test failed:

```
E0417 08:51:40.397144    5651 sync.go:295] getBlockWorker 3 connect block error Block not found. Exiting...
E0417 08:51:40.397574    5651 sync.go:295] getBlockWorker 6 connect block error Block not found. Exiting...
E0417 08:51:40.397617    5651 sync.go:295] getBlockWorker 4 connect block error Block not found. Exiting...
--- FAIL: TestIntegration (3.40s)
    --- FAIL: TestIntegration/viacoin=main (3.32s)
        --- FAIL: TestIntegration/viacoin=main/rpc (0.01s)
            rpc.go:55: Failed loading of test data: invalid character ']' looking for beginning of value
        --- FAIL: TestIntegration/viacoin=main/sync (3.03s)
```

**Comment by romanornr** [comment]
Just force pushed the fix. There was an extra ","

**Comment by martinboehm** [comment]
It is still failing, with different error:

```
        --- FAIL: TestIntegration/viacoin=main/sync (0.58s)
            --- PASS: TestIntegration/viacoin=main/sync/ConnectBlocksParallel (0.19s)
                --- PASS: TestIntegration/viacoin=main/sync/ConnectBlocksParallel/verifyBlockInfo (0.00s)
                --- PASS: TestIntegration/viacoin=main/sync/ConnectBlocksParallel/verifyTransactions (0.00s)
                --- PASS: TestIntegration/viacoin=main/sync/ConnectBlocksParallel/verifyAddresses (0.00s)
            --- PASS: TestIntegration/viacoin=main/sync/ConnectBlocks (0.21s)
                --- PASS: TestIntegration/viacoin=main/sync/ConnectBlocks/verifyBlockInfo (0.00s)
                --- PASS: TestIntegration/viacoin=main/sync/ConnectBlocks/verifyTransactions (0.00s)
                --- PASS: TestIntegration/viacoin=main/sync/ConnectBlocks/verifyAddresses (0.00s)
            --- FAIL: TestIntegration/viacoin=main/sync/HandleFork (0.19s)
                handlefork.go:34: Upper block height mismatch: 1503793 != 1503796
```

I would really like if you could do the tests before requesting me to do it.

**Comment by romanornr** [comment]
Trying now with ```make test-all ARGS="-run TestBitcoin"```
Seems like it will run the unit tests

**Comment by martinboehm** [comment]
The test which failed was run using the following command:
```
make test-integration ARGS="-v -run=TestIntegration/viacoin=main"
```

**Comment by romanornr** [comment]
I think it passes now

sudo make test-integration ARGS="-v -run=TestIntegration/viacoin=main"
```
cd /go/src/blockbook && go test -tags integration `go list blockbook/tests/...` -v -run=TestIntegration/viacoin=main
=== RUN   TestIntegration
=== RUN   TestIntegration/viacoin=main
=== RUN   TestIntegration/viacoin=main/rpc
=== RUN   TestIntegration/viacoin=main/rpc/GetBlock
=== RUN   TestIntegration/viacoin=main/rpc/GetBlockHash
=== RUN   TestIntegration/viacoin=main/rpc/GetTransaction
=== RUN   TestIntegration/viacoin=main/rpc/GetTransactionForMempool
=== RUN   TestIntegration/viacoin=main/rpc/MempoolSync
=== RUN   TestIntegration/viacoin=main/rpc/EstimateSmartFee
=== RUN   TestIntegration/viacoin=main/rpc/GetBestBlockHash
=== RUN   TestIntegration/viacoin=main/rpc/GetBestBlockHeight
=== RUN   TestIntegration/viacoin=main/rpc/GetBlockHeader
=== RUN   TestIntegration/viacoin=main/sync
=== RUN   TestIntegration/viacoin=main/sync/ConnectBlocksParallel
=== RUN   TestIntegration/viacoin=main/sync/ConnectBlocksParallel/verifyBlockInfo
=== RUN   TestIntegration/viacoin=main/sync/ConnectBlocksParallel/verifyTransactions
=== RUN   TestIntegration/viacoin=main/sync/ConnectBlocksParallel/verifyAddresses
=== RUN   TestIntegration/viacoin=main/sync/ConnectBlocks
=== RUN   TestIntegration/viacoin=main/sync/ConnectBlocks/verifyBlockInfo
=== RUN   TestIntegration/viacoin=main/sync/ConnectBlocks/verifyTransactions
=== RUN   TestIntegration/viacoin=main/sync/ConnectBlocks/verifyAddresses
=== RUN   TestIntegration/viacoin=main/sync/HandleFork
--- PASS: TestIntegration (0.51s)
    --- PASS: TestIntegration/viacoin=main (0.51s)
        --- PASS: TestIntegration/viacoin=main/rpc (0.00s)
            --- PASS: TestIntegration/viacoin=main/rpc/GetBlock (0.00s)
            --- PASS: TestIntegration/viacoin=main/rpc/GetBlockHash (0.00s)
            --- PASS: TestIntegration/viacoin=main/rpc/GetTransaction (0.00s)
            --- PASS: TestIntegration/viacoin=main/rpc/GetTransactionForMempool (0.00s)
            --- SKIP: TestIntegration/viacoin=main/rpc/MempoolSync (0.00s)
                rpc.go:345: Skipping test, mempool is empty
            --- PASS: TestIntegration/viacoin=main/rpc/EstimateSmartFee (0.00s)
            --- PASS: TestIntegration/viacoin=main/rpc/GetBestBlockHash (0.00s)
            --- PASS: TestIntegration/viacoin=main/rpc/GetBestBlockHeight (0.00s)
            --- PASS: TestIntegration/viacoin=main/rpc/GetBlockHeader (0.00s)
        --- PASS: TestIntegration/viacoin=main/sync (0.50s)
            --- PASS: TestIntegration/viacoin=main/sync/ConnectBlocksParallel (0.14s)
                --- PASS: TestIntegration/viacoin=main/sync/ConnectBlocksParallel/verifyBlockInfo (0.00s)
                --- PASS: TestIntegration/viacoin=main/sync/ConnectBlocksParallel/verifyTransactions (0.00s)
                --- PASS: TestIntegration/viacoin=main/sync/ConnectBlocksParallel/verifyAddresses (0.00s)
            --- PASS: TestIntegration/viacoin=main/sync/ConnectBlocks (0.18s)
                --- PASS: TestIntegration/viacoin=main/sync/ConnectBlocks/verifyBlockInfo (0.00s)
                --- PASS: TestIntegration/viacoin=main/sync/ConnectBlocks/verifyTransactions (0.00s)
                --- PASS: TestIntegration/viacoin=main/sync/ConnectBlocks/verifyAddresses (0.00s)
            --- PASS: TestIntegration/viacoin=main/sync/HandleFork (0.18s)
PASS
ok      blockbook/tests 0.565s
?       blockbook/tests/dbtestdata      [no test files]
?       blockbook/tests/rpc     [no test files]
?       blockbook/tests/sync    [no test files]
```

sudo make test-integration ARGS="-run=TestIntegration/viacoin/"
```
Image blockbook-build is up to date
docker run -t --rm -e PACKAGER=0:0 -e UPDATE_VENDOR=1 -v /home/romano/go/src/blockbook:/src --network="host" blockbook-build make test-integration ARGS="-run=TestIntegration/viacoin/"
rm -rf /go/src/blockbook
cp -r /src /go/src/blockbook
make prepare-vendor
make[1]: Entering directory '/build'
Updating vendor
make[1]: Leaving directory '/build'
cd /go/src/blockbook && packr clean && packr
cd /go/src/blockbook && go test -tags integration `go list blockbook/tests/...` -run=TestIntegration/viacoin/
ok      blockbook/tests 0.526s
?       blockbook/tests/dbtestdata      [no test files]
?       blockbook/tests/rpc     [no test files]
?       blockbook/tests/sync    [no test files]
```

Any other tests I'm supposed to run/missed?

**Comment by martinboehm** [comment]
That's it :)

**Pull request merged**
