### PR TITLE
Support Polis

### PR DESCRIPTION
**Pull request by eabz**

### CODE REVIEW

**Comment by martinboehm** [comment]
Hi, I tried to build the package, however I get error during build:
```
rm: cannot remove 'backend/bin/polis-qt': No such file or directory
```
I think you should remove polis-qt from the polis.json:
```
"exclude_files": [
   "bin/polis-qt"
], 
```

**Comment by eabz** [comment]
@martinboehm Removed, thanks for pointing.

**Comment by martinboehm** [comment]
Sorry, the backend package is still incorrect, there is another problem. You expect to run `polisd` from the path `{{.Env.BackendInstallPath}}/{{.Coin.Alias}}/bin/polisd`, however `polisd` is extracted to `{{.Env.BackendInstallPath}}/{{.Coin.Alias}}/polisd`.

Please try to build and run your application using the docker build.

**Comment by eabz** [comment]
@martinboehm Thanks for pointing it. I am really sorry I didn't test it. I'll change it to WIP until I have successfully tested.

**Comment by eabz** [comment]
@martinboehm Ready: https://blockbook.polispay.org/

**Comment by martinboehm** [comment]
Now I can run Polis in our test environment. However, your PR does not contain any tests, could you please add them? You can use for example [this PR](https://github.com/trezor/blockbook/pull/68/files) as a reference of what should be done.

**Comment by eabz** [comment]
@martinboehm 
Sorry for delay. 
TestInfo is ready.

**Comment by martinboehm** [comment]
Hi, I tried to build the packages and got the following error:
```
dpkg-shlibdeps: error: cannot find library libX11-xcb.so.1 needed by debian/backend-polis/opt/coins/nodes/polis/bin/polis-qt (ELF format: 'elf64-x86-64' abi: '0201003e00000000'; RPATH: '')
```
It seems that now you should add back

```
"exclude_files": [
   "bin/polis-qt"
],  
```
:)

**Comment by eabz** [comment]
Thanks for pointing @martinboehm seems the last update included the -qt version.

**Comment by martinboehm** [comment]
And also please add integration tests.

**Comment by eabz** [comment]
@martinboehm Done

**Comment by martinboehm** [comment]
The sync integration test fails, there is probably a problem in the sync json file:
```
--- FAIL: TestIntegration/polis=main/sync (0.00s)
            sync.go:66: Failed loading of test data: invalid character '}' looking for beginning of object key string
```

**Comment by eabz** [comment]
Yes, there was a typo.

**Comment by martinboehm** [comment]
All's well that ends well :)

**Pull request merged**
