### PR TITLE
EVM Abstraction

### PR DESCRIPTION
**Pull request by kaladinlight**
- add common evm interfaces
- chain specific implementations compose `EthereumRPC` and implement the necessary evm interfaces. this largely provides the ability to use chain specific types (unique dependencies) while still leveraging the base ethereum logic
- expose struct values necessary for initializing on a chain specific basis
- move chain specific configuration to `Initialize()`

**Avalanche Examples:**
avax-dashboard
image

**Ethereum Example (I don't have an archive node to point to at the moment...):**
image

### CODE REVIEW

**Comment by kaladinlight** [comment]
Well it looks like I need to fix the commit history, but you can see the proposed changes in the final commits by me. Working sync for both eth and avax (avax with an archive node showing internal txs).

Notes:
- there seems to be a race condition on shutdown regarding closing the `chanSyncIndex` channel with a pending notification send
- not sure how often the 4byte directory is updated, but the thought crossed my mind to either add missing sig hashes to help improve the db, or cache missed ones and occasionally try to refetch and store to try and populate more without having to restart blockbook to trigger the download again (might be missing something here as I didn't dig too deep)

**Comment by kaladinlight** [comment]
Add Avalanche PR: https://github.com/kaladinlight/blockbook/pull/5

**Comment by martinboehm** [comment]
Also, I made a couple of comments to your Avalanche PR.

**Comment by martinboehm** [comment]
@kaladinlight looks good, thank you! Unfortunately I force pushed to the v0.4.0 branch, could you please rebase your code again to get rid of the conflicts? I promise not to do it again before I merge this PR :)

**Comment by kaladinlight** [comment]
> @kaladinlight looks good, thank you! Unfortunately I force pushed to the v0.4.0 branch, could you please rebase your code again to get rid of the conflicts? I promise not to do it again before I merge this PR :)

Ok, just rebased so we should be good to go :) Let me know f there is anything else, and I will wait on your merge and open up the avalanche pr officially from there. Thanks!

**Comment by martinboehm** [comment]
When syncing my Goerli Testnet on my dev machine with backend on remote server, I am getting intermittent errors `context deadline exceeded` which I have not seen before, especially in case of `GetBlockHash`. When I run the branch `v0.4.0`, these issues do not appear. 

```
E1215 10:48:44.450535   53235 ethrpc.go:649] debug_traceBlockByHash block 0x09397a03f6dc06ee57434eb74c4a3c1ad88c0d4933a0350a1cb489cf59a49368, error context deadline exceeded
E1215 10:48:44.995888   53235 sync.go:377] GetBlockHash error height 8134527: context deadline exceeded
E1215 10:48:44.996955   53235 ethrpc.go:649] debug_traceBlockByHash block 0x978077b142be3a8e669a7752f366d4c008b1c3bd3ab35565f71a19241673e390, error context deadline exceeded
E1215 10:48:45.020676   53235 ethrpc.go:649] debug_traceBlockByHash block 0x7c6fc53bd02986e7aa8e9b3d9c6180842f8e2c3f411962dd6771fe620c6f5cb9, error context deadline exceeded
E1215 10:50:13.434290   53235 sync.go:377] GetBlockHash error height 8134527: websocket: close 1006 (abnormal closure): unexpected EOF
```

I am trying to figure out what could have changed but do not see anything obvious. Do you have some clue?

**Comment by kaladinlight** [comment]
> When syncing my Goerli Testnet on my dev machine with backend on remote server, I am getting intermittent errors `context deadline exceeded` which I have not seen before, especially in case of `GetBlockHash`. When I run the branch `v0.4.0`, these issues do not appear.
> 
> ```
> E1215 10:48:44.450535   53235 ethrpc.go:649] debug_traceBlockByHash block 0x09397a03f6dc06ee57434eb74c4a3c1ad88c0d4933a0350a1cb489cf59a49368, error context deadline exceeded
> E1215 10:48:44.995888   53235 sync.go:377] GetBlockHash error height 8134527: context deadline exceeded
> E1215 10:48:44.996955   53235 ethrpc.go:649] debug_traceBlockByHash block 0x978077b142be3a8e669a7752f366d4c008b1c3bd3ab35565f71a19241673e390, error context deadline exceeded
> E1215 10:48:45.020676   53235 ethrpc.go:649] debug_traceBlockByHash block 0x7c6fc53bd02986e7aa8e9b3d9c6180842f8e2c3f411962dd6771fe620c6f5cb9, error context deadline exceeded
> E1215 10:50:13.434290   53235 sync.go:377] GetBlockHash error height 8134527: websocket: close 1006 (abnormal closure): unexpected EOF
> ```
> 
> I am trying to figure out what could have changed but do not see anything obvious. Do you have some clue?

Does this happen in both initial sync and stay synced modes? I would assume you are using the same config file with same timeout in both cases. Super odd because I don't even create a `CallContext` handler function locally, it is just using the wrapped `rpc.Client` call directly...

I will work on recereating locally and see if I can track anything down. Stay tuned

**Comment by martinboehm** [comment]
In the initial sync(or better bulk mode when my local DB is being synced to the last block after it was off for some time). I use the same config, actually everything is the same except for the branch. 
I cannot exclude some weird network issues, however I tried 2 times v0.4.0 branch and 2 times your branch and the issue happened only in your branch and I have never seen such issue before. 
On the other hand, I am running now the initial sync of the Goerli testnet on our dev server (with both backend and Blockbook on the same machine) and it imported first 3000000 blocks without any issue so far.

**Comment by kaladinlight** [comment]
Interesting... That does point to network issues to me, but definitely odd in you back to back comparison. I have been running this morning and haven't noticed anything yet (haven't done the bulk mode yet though). There isn't really any logic changes to speak of, just the interface abstraction which is the weird part. Biggest difference was around the channel management, but even that should behave in the same manner.

I did have to set the `OpenRPC` function so we open up the same connections on reconnect, but that only showed on avalanche integration since it was using the ethereum `openRPC` function on reconnect.

I will play around with it a bit more, but nothing is immediately apparent

**Comment by martinboehm** [comment]
I just finished syncing goerli testnet without any issue, I am calling my problems weird network issues.

**Comment by martinboehm** [comment]
Thank you! We can continue with the Avalanche PR.

**Pull request merged**
