### PR TITLE
Viacoin

### PR DESCRIPTION
**Pull request by romanornr**

### CODE REVIEW

**Comment by romanornr** [comment]
This can be rebased into 1 commit if preferred.

**Comment by martinboehm** [comment]
Thank you very much for your contribution! Do you have somewhere a running, publicly accessible instance of Viacoin blockbook, so that we could run checks against it?

**Comment by romanornr** [comment]
If I'm correct, an email has been sent with the public accessible instance of Viacoin blockbook

**Comment by martinboehm** [comment]
I have been able to test the viacoin blockbook on Friday. It seemed almost OK. 

The only issue I noticed were not working ZeroMQ notifications of new blocks and mempool transactions. It seems the problem is in `viacoin.json`, where the ZeroMQ port does not match the backend port.

**Comment by romanornr** [comment]
Thanks, I will look into that ZeroMQ non matching port today.

**Comment by romanornr** [comment]
The other dev @chainfailure was running the public instance.

He just updated his config file with ZMQ ports. 
Can you test it again?

**Comment by martinboehm** [comment]
Hi, we have completely reworked (simplified) the way debian packages are created. It is already pushed to `master`, if you want to check it or you can wait a couple of days until we document it. 

What is the idea behind the change:

1) there is only one file which defines the coin packages: `<coin>.json` in `configs/coins`. The file defines all coin, backend and blockbook specifics. The packages are then generated from this file.
2) we have added verification of the backend binary, so that the package is not created with faulty or malicious binary. The verification is controlled by `"verification"` and `"verification_source"` entries in the config json file.

**Comment by romanornr** [comment]
Should be fixed now. 

cc @chainfailure please update your public instance from github.com/viacoin/blockbook

**Comment by martinboehm** [comment]
Hi, I run the package build on our dev server and got a unit test failure:

`--- FAIL: Test_UnpackTx (0.00s)
    --- FAIL: Test_UnpackTx/viacoin-1 (0.00s)
    	viacoin_test.go:205: unpackTx() got = &{0200000001ddc431a8f5c4e74296de8a6bff796ece148b9bd6827a80ecde8671df41a51fc7000000006a47304402204f929a1e1e40bd352bbd5d3c5ae6c29740e5a8b29dd8c53a15d3eab29aecee7c02206a514e5e4561cfb9330d98f4a4fe1385af56d87eb1d3e1a379d7a50276788cfe0121034a9305644fbcb56d4fc0bc15959b917f7753ae8e581acc97f9cfe771ad1e8249feffffff0200ca9a3b000000001976a91456c7359ed52d61c1ca371d7dc136632148169c5e88acd0e8cc10000000001976a914112e29df5df4866e40ef98e0857036b275380fe088ac6ab94e00 d0284c75a389a07cc256e0bb913110d8d8059efd04daa8147ecf2fa0b3bdf6ff 2 5159274 [{ c71fa541df7186deec807a82d69b8b14ce6e79ff6b8ade9642e7c4f5a831c4dd 0 {47304402204f929a1e1e40bd352bbd5d3c5ae6c29740e5a8b29dd8c53a15d3eab29aecee7c02206a514e5e4561cfb9330d98f4a4fe1385af56d87eb1d3e1a379d7a50276788cfe0121034a9305644fbcb56d4fc0bc15959b917f7753ae8e581acc97f9cfe771ad1e8249} 4294967294 []}] [{10 0 {76a91456c7359ed52d61c1ca371d7dc136632148169c5e88ac [VhuffXKNA3j9hgp2JYGrj6uHQ6KUU6zNbS]} VhuffXKNA3j9hgp2JYGrj6uHQ6KUU6zNbS} {2.818644 1 {76a914112e29df5df4866e40ef98e0857036b275380fe088ac [VbZfhUMCUJHDjqjby6ynYFPZSNVYhfe4cK]} VbZfhUMCUJHDjqjby6ynYFPZSNVYhfe4cK}] 0 0 1530319242}, want &{0200000001ddc431a8f5c4e74296de8a6bff796ece148b9bd6827a80ecde8671df41a51fc7000000006a47304402204f929a1e1e40bd352bbd5d3c5ae6c29740e5a8b29dd8c53a15d3eab29aecee7c02206a514e5e4561cfb9330d98f4a4fe1385af56d87eb1d3e1a379d7a50276788cfe0121034a9305644fbcb56d4fc0bc15959b917f7753ae8e581acc97f9cfe771ad1e8249feffffff0200ca9a3b000000001976a91456c7359ed52d61c1ca371d7dc136632148169c5e88acd0e8cc10000000001976a914112e29df5df4866e40ef98e0857036b275380fe088ac6ab94e00 d0284c75a389a07cc256e0bb913110d8d8059efd04daa8147ecf2fa0b3bdf6ff 0 5159274 [{ c71fa541df7186deec807a82d69b8b14ce6e79ff6b8ade9642e7c4f5a831c4dd 0 {47304402204f929a1e1e40bd352bbd5d3c5ae6c29740e5a8b29dd8c53a15d3eab29aecee7c02206a514e5e4561cfb9330d98f4a4fe1385af56d87eb1d3e1a379d7a50276788cfe0121034a9305644fbcb56d4fc0bc15959b917f7753ae8e581acc97f9cfe771ad1e8249} 4294967294 []}] [{10 0 {76a91456c7359ed52d61c1ca371d7dc136632148169c5e88ac [VhuffXKNA3j9hgp2JYGrj6uHQ6KUU6zNbS]} VhuffXKNA3j9hgp2JYGrj6uHQ6KUU6zNbS} {2.818644 1 {76a914112e29df5df4866e40ef98e0857036b275380fe088ac [VbZfhUMCUJHDjqjby6ynYFPZSNVYhfe4cK]} VbZfhUMCUJHDjqjby6ynYFPZSNVYhfe4cK}] 0 0 1530319242}
FAIL
FAIL	blockbook/bchain/coins/viacoin	0.037s
`

Could you please check it?

**Comment by romanornr** [comment]
Should be fixed now. 
``` romano@arch  ~/go/src/blockbook/bchain/coins/viacoin   master ●  go test
PASS
ok      blockbook/bchain/coins/viacoin  0.021s
```

**Comment by martinboehm** [comment]
Hi. I am sorry for keeping you waiting. We have reworked Blockbook a lot. If you are still interested in implementing Viacoin in Blockbook, could you please rebase the PR to the newest code base? I will give you support if you have some questions/problems.

**Comment by martinboehm** [comment]
Replaced by #88

**Pull request closed without merging**
