### PR TITLE
Update Decred

### LINKED ISSUE #384: Update Decred
The current version of decred blockbook uses (1.4.0) will fork off mainnet in 8 days due to a consensus change.

### PR DESCRIPTION
**Pull request by dajohi**
This upgrades blockbook to use Decred 1.5.1.

This is built on top of #374 
Closes #384

### CODE REVIEW

**Comment by martinboehm** [comment]
Hi, I had finally time to merge the go mod support to master. Could you please finalize this PR so that it can be merged?
Maybe it would make more sense to recreate it so that the change set does not include already merged modules support.

**Comment by milesmanley** [comment]
Hey @dajohi hope you are well - do you plan to finalise this soon?

**Comment by dajohi** [comment]
@martinboehm @milesmanley updated

**Comment by martinboehm** [comment]
Hi, I built decred backend but when I installed it, it did not start correctly as it does not have the `decred.conf` file specified in the service:
```
ExecStart=/opt/coins/nodes/decred/dcrd --datadir=/opt/coins/data/decred/backend --appdata=/opt/coins/data/decred -C=/opt/coins/nodes/decred/decred.conf
```

```
> $ ll /opt/coins/nodes/decred                                                                                                                                                                                                                                                  [±dajohi-decred ✓]
Permissions Size User Date Modified Name
.rwxr-xr-x  7.2M root 17 Sep 20:31  dcrctl
.rwxr-xr-x   14M root 17 Sep 20:31  dcrd
.rwxr-xr-x   19M root 17 Sep 20:31  dcrlncli
.rwxr-xr-x   27M root 17 Sep 20:31  dcrlnd
.rwxr-xr-x   16M root 17 Sep 20:31  dcrwallet
.rwxr-xr-x   15M root 17 Sep 20:31  politeiavoter
.rwxr-xr-x  1.5M root 17 Sep 20:31  promptsecret
.rw-r--r--   907 root  1 Jan  1970  sample-dcrctl.conf
.rw-r--r--   13k root  1 Jan  1970  sample-dcrd.conf
.rw-r--r--   11k root  1 Jan  1970  sample-dcrlnd.conf
.rw-r--r--  8.2k root  1 Jan  1970  sample-dcrwallet.conf
.rw-r--r--  2.9k root  1 Jan  1970  sample-politeiavoter.conf
```

**Comment by dajohi** [comment]
@martinboehm i rebased and updated.  can you give it another try?  if it doesn't work, any idea why?

**Pull request merged**
