### PR TITLE
Groestlcoin (GRS) support

### PR DESCRIPTION
**Pull request by yura-pakhuchiy**
This PR incorporates feedback from https://github.com/trezor/blockbook/pull/30. Now GRS uses parser similar to Zcash and all GRS specific code is in `bchain/coins/groestlcoin`. I've not updated it to new packaging system yet (pushed few hours ago). Please review everything else.

I've setup servers compiled from this branch:
https://blockbook.groestlcoin.org:9145/test.html  - mainnet
https://blockbook-test.groestlcoin.org:19145/test.html - testnet
All operations from testpage seem to work (including subscribeAddressTxid which have not worked in previous PR).

Parser does not validate checksum for P2SH and P2PKH addresses due to missing Groestl hash in Go and acts as if address with correct checksum was provided. This can be seen as both a bug and a feature (see below).

I've played with wallet.trezor.io a bit more and here is what happens (I might be wrong, because I have only minified sources and all conclusions is just from my observations). Wallet requests bitcoin y/xpub from Trezor and generates GRS addresses from it using JS code (probably for performance reasons, because it faster than fetch addresses one by one from Trezor). Main part of generated addresses is correct, but checksum is wrong. Then wallet sends requests to GRS blockbook for addresses history. As noted above, blockbook tolerates invalid checksum and returns transaction history. Then wallet even displays account balance for a fraction of second. But then wallet starts to ask Trezor for addresses and compare them to ones it generated. At this point wallet notices the difference in checksums and raises 'Inconsistent state' exception. I see 2 ways to fix this:
1. The proper way is to request GRS x/ypubs from Trezor instead of Bitcoin ones (they differ only in checksum) and then use JS similar to https://groestlcoin.org/bip39-standalone.html (GRS fork of Ian Coleman's tool) to generate GRS addresses with correct checksum. BIP39 tool sources are available at https://github.com/Groestlcoin-Archives/bip39.
2. Might be an easier way is to continue generating addresses with wrong checksum and then just update checksum to correct one from either blockbook replies or from Trezor replies.

### CODE REVIEW

**Comment by yura-pakhuchiy** [comment]
@prusnak Could you please reconsider GRS support in webwallet? All GRS specific code now is in `bchain/coins/groestlcoin`, there is no change in vendored dependencies and PR size is comparable to PRs with other coins. Please see PR description with my observations regarding wallet.trezor.io support.

**Comment by gruve-p** [comment]
@martinboehm Can we have your input on this please?

**Comment by martinboehm** [comment]
Hi, I checked the blockbook servers and code, it looks good.
Could you please update the packaging system so that I can build and test it locally?

About the checksum problem: I think the only correct way is to implement GRS support in wallet, however I am not the one to decide it.

**Comment by yura-pakhuchiy** [comment]
@martinboehm thank you! I've updated the packaging system and rebased the PR.

**Comment by gruve-p** [comment]
@martinboehm Are you able to build and test it locally or does it need any other changes? Any feedback would be welcome

**Comment by martinboehm** [comment]
Hi, I have finally found time to review your pull request. I was able to build and install both groestlcoin backend and blockbook, it seems to run fine. 

However, there are no parser and rpc tests available in your PR. Could you please add them?

Also, could you please base your pull request on blockbook branch `v0.0.7`? We are going to release this version soon and I would like to merge your PR to this branch. There is currently a bug in the `master` branch (fixed in `v0.0.7`), which causes that RPC integration tests are not correctly run.

**Comment by yura-pakhuchiy** [comment]
@martinboehm I've checked 0.0.7 branch and Zcash now uses forked version of btcutil instead of providing `GetAddrIDFromVout` and `GetAddrIDFromAddress`. Should I submit GRS patch to this btcutil fork?

**Comment by gruve-p** [comment]
@martinboehm Can you please comment on the above so we can continue the rebase on top of v0.0.7 (and add tests) so this PR can be merged in that branch.

**Comment by martinboehm** [comment]
I would recommend you to wait couple of days, we are almost ready to merge `v0.0.7` and integration `tests` branches to `master`. Then you will have a more stable codebase to merge your changes.

**Comment by jakm** [comment]
@yura-pakhuchiy please, keep GRS implementation in blockbook, principle should be the same

**Comment by martinboehm** [comment]
Hi, we have merged the branch `v0.0.7` to `master` so you can base your code again to `master`. 
If you need changes in `btcutil`, go ahead and make pull request there. I would still regard `Zcash` as the template, which you should follow in your implementation.

**Comment by yura-pakhuchiy** [comment]
@martinboehm I've updated the PR. Changes from previous versions:
1. Updated to the latest `master`.
2. Includes unit, RPC and sync tests.
3. Enforces correct address checksum for addresses.
4. Depends on https://github.com/jakm/btcutil/pull/2 to minimize amount of duplicated code (also will make implementation of some other coins easier in the future). Also https://github.com/jakm/bchutil/pull/1 required to fix compilation after API changes in `btcutil`.

Looking forward your review!

**Comment by martinboehm** [comment]
I have merged your PRs for `btcutil` and `bchutil` projects. Could you please set the new versions to `Gopkg.lock`, I will then build and run your PR.

**Comment by yura-pakhuchiy** [comment]
Oops, I forgot to add github.com/Groestlcoin/go-groestl-hash/groestl to deps.

**Comment by yura-pakhuchiy** [comment]
Updated again and verified that it builds and works.

**Comment by martinboehm** [comment]
Hi, I tested your implementation, it looks good. However, we have to fix dependencies:
We have added `github.com/Groestlcoin/go-groestl-hash/groestl` dependency to the `btcutil` project, where it belongs. Please, in your Blockbook, set again the new versions of `btcutil` and `bchutil` projects  and remove dependecy to `github.com/Groestlcoin/go-groestl-hash/groestl`, in `Gopkg.lock`.

**Comment by yura-pakhuchiy** [comment]
Martin, I've updated deps and removed `go-groestl-hash` from blockbook. However now it fails to build:
```
cd /go/src/blockbook && go build -o /build/blockbook -ldflags="-s -w -X blockbook/common.version=devel -X blockbook/common.gitcommit=5dfa073 -X blockbook/common.buildtime=2018-10-18T13:03:06+00:00" 
vendor/github.com/jakm/btcutil/base58/base58check.go:10:2: cannot find package "github.com/Groestlcoin/go-groestl-hash/groestl" in any of:
	/go/src/blockbook/vendor/github.com/Groestlcoin/go-groestl-hash/groestl (vendor tree)
	/opt/go/src/github.com/Groestlcoin/go-groestl-hash/groestl (from $GOROOT)
	/go/src/github.com/Groestlcoin/go-groestl-hash/groestl (from $GOPATH)
Makefile:13: recipe for target 'build' failed
```
I guess we still need `go-groestl-hash` in `Gopkg.lock` for Blockbook.

**Comment by martinboehm** [comment]
If you build in docker, rebuild images, please. If you build it manually, remove `vendor` folder and run `dep ensure -vendor-only`.

**Comment by yura-pakhuchiy** [comment]
Hm, I just did `make build-images` to rebuild images. `make` still fails with the same error. But never mind, if it works for you just ignore me.

**Comment by martinboehm** [comment]
Yes, seems that `github.com/Groestlcoin/go-groestl-hash/groestl` must be added to `Gopkg.lock` also in Blockbook. Sorry for confusion.

**Comment by yura-pakhuchiy** [comment]
I've pushed update with just `{btc,bch}utils` hashes update, but leaving Groestl hash in place.

**Comment by martinboehm** [comment]
Hopefully the last thing. In the rollback test, you have to use fake blocks with hash of real block, so that Blockbook can get them from backend. I used hashes for blocks 2200713 and 2200714. We will mention this in the documentation, you couldn't have known it.

```
"fakeBlocks": {
    "2200744": {
        "height": 2200744,
        "hash": "00000000000091c2f138f8e97dfda7256f8aee2d4ee4ad52cefbad837ca50a99"
    },
    "2200743": {
        "height": 2200743,
        "hash": "000000000001596f4fd5ba68aa7a7e09d1a28096ea520940080fb1c128ca13a4"
    }

```

**Comment by yura-pakhuchiy** [comment]
Ah, it makes sense now. Actually I have used hash of real blocks from `getchaintips` output, but was wondering how it is sustainable.
```
# /opt/coins/nodes/groestlcoin/bin/groestlcoin-cli -conf=/opt/coins/nodes/groestlcoin/groestlcoin.conf getchaintips | grep 000000000000e0155651c46606c724f2b1eeb2185a86a853456fbc8313cec262 -C3
  },
  {
    "height": 2200744,
    "hash": "000000000000e0155651c46606c724f2b1eeb2185a86a853456fbc8313cec262",
    "branchlen": 2,
    "status": "valid-fork"
  },
```
Updated.

**Comment by gruve-p** [comment]
RegtestMagic wire.BitcoinNet = 0x0709110b
not needed in bchain/coins/grs/grsparser.go ?

**Comment by yura-pakhuchiy** [comment]
I do not think it is required since Blockbook supports only mainnet and testnet chains.

**Comment by gruve-p** [comment]
Are we still using dummy value for MainnetMagic wire.BitcoinNet ?
MainnetMagic wire.BitcoinNet = 0xd9b4bef9 // correct value 0xd4b4bef9
TestnetMagic wire.BitcoinNet = 0x0709110b // correct value but same as bitcoin testnet

**Comment by martinboehm** [comment]
It is not necessary to use dummy values for magic numbers any more, the coins should be completely separated now. On the other hand, for Blockbook is the used number useless, you can use any number.

**Comment by yura-pakhuchiy** [comment]
@gruve-p have you updated net number recently? I think I've got number 0xd9b4bef9 from 2.16.0 release and it was the same as in Bitcoin.

**Comment by martinboehm** [comment]
Is it now as you want it or should I wait with merge?

**Comment by yura-pakhuchiy** [comment]
From my side - everything is ready. @gruve-p any more comments?

**Comment by gruve-p** [comment]
@martinboehm @yura-pakhuchiy LGTM

**Comment by martinboehm** [comment]
Thanks for cooperation!

**Comment by yura-pakhuchiy** [comment]
Thank you for guidance and review, Martin!

**Comment by yura-pakhuchiy** [comment]
Is there anything we can do to help with web wallet integration? There are various JS libraries available to generate GRS addresses:
https://github.com/Groestlcoin/groestlcoinjs-lib/tree/3.1.1
https://github.com/Groestlcoin/groestlcoinjs-lib/tree/3.3.2
https://github.com/Groestlcoin/groestlcoinjs-lib/tree/4.0.2
https://github.com/Groestlcoin/groestlcoinjs-lib
https://github.com/Groestlcoin/bs58grscheck
https://github.com/Groestlcoin/bip32grs
https://github.com/Groestlcoin/wifgrs

**Comment by martinboehm** [comment]
Sorry, I cannot help you with the web wallet, I am not working on this project. Try to get in touch with @prusnak, he may point you in the right direction.

**Pull request merged**
