### PR TITLE
Groestlcoin: Bump to 26.0

### PR DESCRIPTION
**Pull request by gruve-p**

### CODE REVIEW

**Comment by martinboehm** [comment]
Hi @gruve-p. Are you sure that need the block filter settings? They are used for a very specific use case of Trezor Coinjoin. Do you need this functionality?

**Comment by gruve-p** [comment]
Hi @martinboehm We do not need this functionality however it can not harm to keep it in right? Are there any disadvantages to keep it in?

**Comment by martinboehm** [comment]
@gruve-p Apart from slightly higher load of the server (but probably nothing significant) there is not issue. If you want to, I will merge it as it is.

**Comment by gruve-p** [comment]
@martinboehm Please merge it then as it is. Thank you!

**Pull request merged**
