### PR TITLE
WIP: Add gomodules support to all packages

### PR DESCRIPTION
**Pull request by dmigwi**
This is in relation to #341

I thought it wise to make every coin implementation a sub-module to keep coin specific dependencies only limited to the specific coin implementation.

### CODE REVIEW

**Comment by martinboehm** [comment]
Thanks a lot! The submodule for each coin looks like a good idea. However, would not it make it hard to upgrade a library used in all coins to a newer version? But probably, when thinking about it, the global text replace will work fine...

BTW when I try to compile the PR using go build, I get error:

**Comment by dmigwi** [comment]
I have been trying to resolve that error for quite a while. The error is due to go-ethereum packages that don't support gomodules which is why the PR has a *WIP* in its title.. I think the global text replace could help fix that error.

**Comment by martinboehm** [comment]
Hi, please, do not mix unrelated changes to this PR. The commits 0226a6f and 22ecf29 are not within the scope of this PR.
Actually, what is the reason for 0226a6f?
Also, why do you rebuild Blockbook when generating the config files in the contrib/scripts/build-blockchaincfg.sh? This is something I would not like to do.

**Comment by dmigwi** [comment]
Closing this in favour of #374

**Pull request closed without merging**
