### PR TITLE
Add Bellcoin

### PR DESCRIPTION
**Pull request by ilmango-doge**
I made blockbook for Bellcoin at the following URL.
https://bellcoin-blockbook.ilmango.work/

Bellcoin official
https://bellcoin.web4u.jp/
https://github.com/bellcoin-org/bellcoin

### CODE REVIEW

**Comment by martinboehm** [comment]
Hi, can you make the bellcoin backend runnable on Debian 9. When I try to run it, I get errors: 
```
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11'

```
I think the backend must be statically linked with standard libraries.

**Comment by ilmango-doge** [comment]
Thank you for comments.

I also got this error.
I told this issue to the developer and I'm trying to build binary supported for Debian 9.

**Comment by bellflower2015** [comment]
Hello.
I'm the founder of Bellcoin.
I recieved message from @ilmango-doge .
How about this?
https://bellflower.web4u.jp/downloads/bellcoin-1.0.2-linux64-ubuntu1604.tar.gz

**Comment by martinboehm** [comment]
@ilmango-doge could you please put the version created by @bellflower2015 to the config file bellcoin.json so that I can try it again? Thanks

**Comment by ilmango-doge** [comment]
I ran the test locally using this binary, but I got errors.
''' error while loading shared libraries: libboost_system.so.1.58.0: cannot open shared object file: No such file or directory '''
I already told @bellfower2015 about this issue.

**Comment by ilmango-doge** [comment]
I run test locally using this binary, but I got error.

`error while loading shared libraries: libboost_system.so.1.58.0: cannot open shared object file: No such file or directory`
I already told this issue to @bellflower2015 

Thanks

**Comment by ilmango-doge** [comment]
Changed to binary which supports Debian 9.

**Comment by martinboehm** [comment]
When I build the project, the backend signature verification fails:
```
gpg --verify checksum
gpg: Signature made Sun Mar  3 11:39:32 2019 UTC
gpg:                using RSA key 1874C53BE0984769
gpg: WARNING: signature digest conflict in message
gpg: Can't check signature: General error
Makefile:4: recipe for target 'all' failed
```

**Comment by ilmango-doge** [comment]
Thank you for comments.

I fixed this issue.

**Pull request merged**
