### PR TITLE
Add MonetaryUnit (MUE) Support

### PR DESCRIPTION
**Pull request by sotblad**
Blockbook running: http://138.68.172.148:9157

Everything seem to be running good.
Thanks!

### CODE REVIEW

**Comment by martinboehm** [comment]
Hi, thank you for your contribution.
I see that you register `MonetaryUnit Testnet` but you do not provide any config for it. Please remove it or create config for it.

**Comment by sotblad** [comment]
Hey! Removed testnet from the factories.

**Comment by martinboehm** [comment]
Good work! :+1:

**Comment by cryptcoin-junkey** [comment]
@sotblad As I reported in #188, the hash of the tar binary is mismatched. Do you have information about the issue?

**Pull request merged**
