### PR TITLE
add GameCredits (GAME) to Blockbook

### PR DESCRIPTION
**Pull request by samadsajanlal**
This is a revised & squashed version of https://github.com/trezor/blockbook/pull/78

### CODE REVIEW

**Comment by martinboehm** [comment]
Thanks, now I am able to run the backend and the Blockbook without any problems. 
Please add integration tests, [see](/trezor/blockbook/blob/master/docs/testing.md).

**Comment by martinboehm** [comment]
Thanks, now I am able to run the backend and the Blockbook without any problems. 
Please add integration tests, [see](/trezor/blockbook/blob/master/docs/testing.md).

**Comment by martinboehm** [comment]
Thanks, now I am able to run the backend and the Blockbook without any problems. 
Please add integration tests, [see](/trezor/blockbook/blob/master/docs/testing.md).

**Comment by samadsajanlal** [comment]
Hi,
its done :)
```
root@blockbook:~/go/src/blockbook# make test-integration ARGS="-run=TestIntegration/gamecredits/"
Image blockbook-build is up to date
docker run -t --rm -e PACKAGER=0:0 -e UPDATE_VENDOR=1 -v /root/bbtemp:/src --network="host" blockbook-build make test-integration ARGS="-run=TestIntegration/gamecredits/"
rm -rf /go/src/blockbook
cp -r /src /go/src/blockbook
make prepare-vendor
make[1]: Entering directory '/build'
Updating vendor
make[1]: Leaving directory '/build'
cd /go/src/blockbook && packr clean && packr
cd /go/src/blockbook && go test -tags integration `go list blockbook/tests/...` -run=TestIntegration/gamecredits/
ok  	blockbook/tests	0.466s
?   	blockbook/tests/dbtestdata	[no test files]
?   	blockbook/tests/rpc	[no test files]
?   	blockbook/tests/sync	[no test files]
root@blockbook:~/go/src/blockbook# 

```

**Comment by martinboehm** [comment]
Thank you for cooperation!

**Pull request merged**
