### PR TITLE
Add Denarius (DNR)

### PR DESCRIPTION
**Pull request by carsenk**
Added Denarius (DNR) backend support, untested currently.

### CODE REVIEW

**Comment by martinboehm** [comment]
Thank you very much for your contribution!

Before we can merge it, please add parser and rpc tests like we have for other coins and give us a link to a running instance of Denarius blockbook so that we can test it.

Also, the blockbook service (file `build/deb/debian/blockbook-denarius.service`) must know about existing Denarius explorer, parameter `-explorer=https://dogechain.info/` now points to a Dogecoin explorer.

**Comment by carsenk** [comment]
Alright I submitted a fix to point to the correct explorer, I am still in the process of getting it setup on a server, as far as the parser and rpc tests there is no documentation on how to do so?

I will update this with the server IP once it is fully online, does Trezor not host its own servers?

**Comment by carsenk** [comment]
I am attempting to run it on a server, I mainly get this response:

`E0629 04:10:52.201517   23067 blockbook.go:106] rpc: -32601: Method not found Retrying...
E0629 04:10:53.201584   23067 blockbook.go:106] rpc: -32601: Method not found Retrying...
E0629 04:10:54.199544   23067 blockbook.go:106] rpc: -32601: Method not found Retrying...
E0629 04:10:55.201676   23067 blockbook.go:106] rpc: -32601: Method not found Retrying..`

**Comment by martinboehm** [comment]
Blockbook calls rpc method `getblockchaininfo` to get info about the node. It seems that this rpc method is failing with error `Method not found.` Does Denarius node implement this method? If not, you will have to override the `GetBlockChainInfo` and use some corresponding Denarius method instead (maybe `getinfo`).

**Comment by carsenk** [comment]
Thank you, yea I'll give that a try I figured it was calling a non existent method, I will override it to use get info, maybe in a future update we will also include that method.

Will update shortly with server info

**Comment by carsenk** [comment]
Went a little crazy on the commits haha....so it seems to run now, but I am not sure what I should be seeing and it seems to just close automatically, then tried with the resyncindex flag and that seems to get further but states address is already in use:

`root@denariusbook:~/go/src/blockbook# ./blockbook -sync -blockchaincfg=configs/denarius.json -httpserver=127.0.0.1:9041 -socketio=127.0.0.1:9141 -certfile=server/testcert -logtostderr
I0629 20:28:30.405900   29849 blockbook.go:132] Blockbook: {Version:unknown GitCommit:unknown BuildTime:unknown GoVersion:go1.9.2 OSArch:linux/amd64}
I0629 20:28:30.408126   29849 mq.go:60] MQ listening to tcp://127.0.0.1:38341
I0629 20:28:30.408455   29849 mempool_utxo.go:66] mempool: starting with 8*2 sync workers
I0629 20:28:30.408577   29849 denariusrpc.go:38] Chain name
I0629 20:28:30.408652   29849 denariusrpc.go:53] rpc: block chain mainnet
I0629 20:28:30.408722   29849 rocksdb.go:103] rocksdb: open ./data
I0629 20:28:30.422945   29849 https.go:81] http server starting to listen on https://127.0.0.1:9041
E0629 20:28:30.423109   29849 blockbook.go:248] listen tcp 127.0.0.1:9041: bind: address already in use
I0629 20:28:30.423331   29849 sync.go:107] resync: genesis from block 0
E0629 20:28:30.423950   29849 blockbook.go:257] resyncIndex height 0: -32600: Params must be an array
I0629 20:28:30.424126   29849 rocksdb.go:130] rocksdb: close
root@denariusbook:~/go/src/blockbook# ./blockbook -resyncindexperiod 935093 -blockchaincfg=configs/denarius.json -httpserver=127.0.0.1:9041 -socketio=127.0.0.1:9141 -certfile=server/testcert -logtostderr
I0629 20:28:42.846398   29865 blockbook.go:132] Blockbook: {Version:unknown GitCommit:unknown BuildTime:unknown GoVersion:go1.9.2 OSArch:linux/amd64}
I0629 20:28:42.848814   29865 mq.go:60] MQ listening to tcp://127.0.0.1:38341
I0629 20:28:42.849043   29865 mempool_utxo.go:66] mempool: starting with 8*2 sync workers
I0629 20:28:42.849121   29865 denariusrpc.go:38] Chain name
I0629 20:28:42.849190   29865 denariusrpc.go:53] rpc: block chain mainnet
I0629 20:28:42.849249   29865 rocksdb.go:103] rocksdb: open ./data
I0629 20:28:42.862267   29865 socketio.go:115] socketio server starting to listen on wss://127.0.0.1:9141
I0629 20:28:42.870874   29865 https.go:81] http server starting to listen on https://127.0.0.1:9041
E0629 20:28:42.871027   29865 blockbook.go:248] listen tcp 127.0.0.1:9041: bind: address already in use`

**Comment by martinboehm** [comment]
Sorry, but the way you are implementing is not correct. You must not touch any go source files other than `denariusparser.go`, `denariusrpc.go` + their corresponding tests `denariusparser_test.go` and `denariusrpc_test.go`. The only exception is `blockchain.go` where you add your factory by code `blockChainFactories["Denarius"] = denarius.NewDenariusRPC`.

The way you should implement it is that in `denariusrpc.go` you override the method `GetBlockChainInfo` and implement it internally by rpc call `getinfo`.

**Comment by carsenk** [comment]
So how are you overriding GetBlockChainInfo, since it is calling it from the other bitcoinrpc.go and even if only modified from denariusrpc denariusparser? It will complain if just changed from Denarius files since GetInfo() doesn't exist in the rest of the code...when it is setup properly then what should I expect to see?

**Comment by martinboehm** [comment]
Paste the following code to your `denariusrpc.go`:

```
type cmdGetInfo struct {
	Method string `json:"method"`
}

type resGetInfo struct {
	Error  *bchain.RPCError `json:"error"`
	Result struct {
		Chain         string `json:"chain"`
		Blocks        int    `json:"blocks"`
		Headers       int    `json:"headers"`
		Bestblockhash string `json:"bestblockhash"`
	} `json:"result"`
}

func (b *DenariusRPC) GetBlockChainInfo() (string, error) {
	glog.V(1).Info("rpc: getinfo")

	res := resGetInfo{}
	req := cmdGetInfo{Method: "getinfo"}
	err := b.Call(&req, &res)
	if err != nil {
		return "", err
	}
	if res.Error != nil {
		return "", res.Error
	}
	return res.Result.Chain, nil
}
```

**Comment by carsenk** [comment]
Alright, so I committed that, and it did compile/build fine this time as usual. Problem though still remains when trying to run it:

`root@denariusbook:~/go/src/blockbook# ./blockbook -sync -blockchaincfg=configs/denarius.json -httpserver=127.0.0.1:9041 -socketio=127.0.0.1:9141 -certfile=server/testcert -logtostderr

I0629 23:39:29.461294    7464 blockbook.go:132] Blockbook: {Version:unknown GitCommit:unknown BuildTime:unknown GoVersion:go1.9.2 OSArch:linux/amd64}

I0629 23:39:29.465375    7464 mq.go:60] MQ listening to tcp://127.0.0.1:38341
I0629 23:39:29.465531    7464 mempool_utxo.go:66] mempool: starting with 8*2 sync workers
I0629 23:39:29.465607    7464 denariusrpc.go:67] Chain name
I0629 23:39:29.465676    7464 denariusrpc.go:82] rpc: block chain mainnet
I0629 23:39:29.465757    7464 rocksdb.go:103] rocksdb: open ./data
I0629 23:39:29.480467    7464 https.go:81] http server starting to listen on https://127.0.0.1:9041
I0629 23:39:29.488713    7464 sync.go:107] resync: genesis from block 0
E0629 23:39:29.489610    7464 blockbook.go:257] resyncIndex height 0: -32600: Params must be an array
I0629 23:39:29.489868    7464 rocksdb.go:130] rocksdb: close`

**Comment by martinboehm** [comment]
Denarius is probably using old version of Bitcoin code, try to use 
```
s.RPCMarshaler = btc.JSONMarshalerV1{}
```
instead of `JSONMarshalerV2` in the `denariusrpc.go`

**Comment by carsenk** [comment]
Testing it out, seems to at least connect now :+1: Thank you!

Odd error though now with the workers:

```
I0629 23:57:28.259235    8416 blockbook.go:132] Blockbook: {Version:unknown GitCommit:unknown BuildTime:unknown GoVersion:go1.9.2 OSArch:linux/amd64}
I0629 23:57:28.262620    8416 mq.go:60] MQ listening to tcp://127.0.0.1:38341
I0629 23:57:28.262874    8416 mempool_utxo.go:66] mempool: starting with 8*2 sync workers
I0629 23:57:28.262976    8416 denariusrpc.go:67] Chain name
I0629 23:57:28.263049    8416 denariusrpc.go:82] rpc: block chain mainnet
I0629 23:57:28.263135    8416 rocksdb.go:103] rocksdb: open ./data
I0629 23:57:28.277165    8416 https.go:81] http server starting to listen on https://127.0.0.1:9041
I0629 23:57:28.285319    8416 sync.go:107] resync: genesis from block 0
I0629 23:57:28.285954    8416 sync.go:125] resync: parallel sync of blocks 0-977341, using 8 workers
E0629 23:57:28.288245    8416 sync.go:242] getBlockWorker 0 connect block error hash 00000d5dbbda01621cfc16bbc1f9bf3264d641a5dbf0de89fd0182c2c4828fcd: -32601: Method not found. Retrying...
E0629 23:57:28.288741    8416 sync.go:242] getBlockWorker 1 connect block error 1 000000baa038f961abe464baf62c28e01c6844023dacc3ee8e316d7f50787caa: readScript: transaction input signature script is larger than the max allowed size [count 18374969402119421951, max 33554432]. Retrying...
E0629 23:57:28.289265    8416 sync.go:242] getBlockWorker 3 connect block error 3 000004e4e3b04bcd1c65c0c66f5acb8201ae32f3becbeb5b4d4be9f803f9b959: readScript: transaction input signature script is larger than the max allowed size [count 18374969410709356543, max 33554432]. Retrying...
E0629 23:57:28.289557    8416 sync.go:242] getBlockWorker 2 connect block error 2 00000902d5dd1f74069025f2688ece99458e22e6596ec27f0419fdbef89dafd0: readScript: transaction input signature script is larger than the max allowed size [count 18375532356367810559, max 33554432]. Retrying...```

**Comment by martinboehm** [comment]
It seems that the format of the denarius transaction is not compatible with the used bitcoin transaction parser. You can either write your own tx parser or let the node parse the block/transactions for you (i.e. call `getblock` in verbose mode). It is slower but easier. Look at the zcashrpc.go/zcashparser.go, where we took this approach.

**Comment by carsenk** [comment]
Alright, I can kinda see what they have done, can't get it to build with recent changes, fairly tired, will update you on what I get unless you beat me to it here, thanks again for all the help!

**Comment by carsenk** [comment]
So it compiles now, but it seems there is an issue with the resGetBlockThin() in the GetBlock function, I am getting this error now over and over: ```  json: cannot unmarshal object into Go struct field ThinBlock.tx of type string. ```

I tried changing it to resGetBlockFull() but it fails to compile, any suggestions?

**Comment by martinboehm** [comment]
I don't know the Denarius node RPC interface, but it seems it is returning full transactions in the verbose getblock (unlike Zcash, which returns only a list of txids). If that is true, you do not need the code starting with
```
	for _, txid := range res.Result.Txids {
		tx, err := z.GetTransaction(txid)
```
as it is loading tx for each txid. You should have bchain.Block.Txs already filled by the json unmarshall if my assumption is correct.

**Comment by martinboehm** [comment]
Closed due to inactivity. The codebase of this pull request is too old. If you want to implement Denarius, please make a new PR.

**Comment by carsenk** [comment]
Yup I will reopen it, I see you updated a lot so I will get a new repo going and PR

**Pull request closed without merging**
