### PR TITLE
Add Koto

### PR DESCRIPTION
**Pull request by wo01**
I have constructed blockbook for Koto at the following URL.
https://blockbook.kotocoin.info/

### CODE REVIEW

**Comment by martinboehm** [comment]
Thank you for your contribution. 
Could you please use ports xx50? Ports xx49 are already taken.

**Comment by martinboehm** [comment]
When I try to run koto backend, I get the following errors:
`/opt/coins/nodes/koto/bin/kotod: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /opt/coins/nodes/koto/bin/kotod)
/opt/coins/nodes/koto/bin/kotod: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /opt/coins/nodes/koto/bin/kotod)
`
I run it on standard Debian Linux 9 (version 4.9.0-8-amd64 (debian-kernel@lists.debian.org) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) ) #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08)). What is the required Linux version?

**Comment by martinboehm** [comment]
Couple of additional comments:

1) the problem with Koto backend on Debian 9 - I actually think that this should be reported to Koto backend team because they should create the package so that it runs on Debian 9 - all other coins (Bitcoin, Zcash etc) support Debian 9. Are you in touch with the team?
2) sorry, I made a mistake with the port, please use xx51. There were multiple PRs at almost the same time and port xx50 is also already in use.
3) could I ask you to rebase you pull request on `indexv4` branch? It contains a new version of Blockbook, which is almost ready to be merged to the master and released. I would like to skip the retesting of your code in the new version. Apart from changing some dependencies, there should not be a big change to your code. However, you will have to reindex the DB as the format is different and incompatible.

**Comment by wo01** [comment]
Thank you for comments.
1. We are going to build coind to run on Debian 9.
2. OK
3. I understood. I will rebase this PR.

**Comment by martinboehm** [comment]
Hi, I tried to compile your the rebased PR. There is a problem - wrong dependencies to btcd/wire and btcutil - we had to fork these libraries to fix an issue so you have to change the references. Look at some other coin implementations, please.

**Comment by martinboehm** [comment]
Hi, I can build now but the unit test is failing:
```
--- FAIL: TestPackTx (0.00s)
    --- FAIL: TestPackTx/koto-1 (0.00s)
    --- FAIL: TestPackTx/koto-2 (0.00s)
```
Please let me know, when the PR is ready to be merged.

**Comment by wo01** [comment]
@martinboehm 
Thank you for your comment.
I fixed the issue.

**Pull request merged**
