### PR TITLE
add GameCredits to Blockbook

### PR DESCRIPTION
**Pull request by samadsajanlal**
Blockbook is operational at http://107.170.253.207:9144/ (https endpoint: https://blockbook.gamecredits.network) with the settings configured in these commits

This is not the final confirmed location for Blockbook production, but it is the staging server where it can be tested. It may very well end up as our production server.

### CODE REVIEW

**Comment by samadsajanlal** [comment]
One thing that was not clear to me is how to execute the unit tests for the parser that were created. I'm not a go programmer, and I didn't find any concise & to the point documentation that shows how to run it.
I am not using a docker container for my environment, so this may have had something to do with it?

**Comment by martinboehm** [comment]
Hi, thank you for your contribution. 
You can run unit tests without docker by `go test -tags="unittest" ./... ` in the Blockbook root directory.

**Comment by samadsajanlal** [comment]
thanks for the reply! it took a few tries but now my parser is working:

```root@blockbook:~/go/src/blockbook# go test -tags="unittest" ./bchain/coins/gamecredits
ok  	blockbook/bchain/coins/gamecredits	0.048s```

**Comment by martinboehm** [comment]
Hi, built the GameCredits backend package and installed it to our dev server. When I try to start it `sudo systemctl start backend-gamecredits.service,` it seems it is not running in the daemon mode and fails to start properly.

Could you please rebase your pull request to the new master HEAD, we have split the backend config parameter 
```
"config_file": "bitcoin.conf"
```
to two parameters 
```
"server_config_file": "bitcoin_like.conf",
"client_config_file": "bitcoin_like_client.conf",
```
and then make sure that you provide correct parameters so that GameCredits backend runs in daemon mode (maybe it needs some additional parameters?).

**Comment by martinboehm** [comment]
Please do not merge our changes to your code. Rebase your changes on our code, so that only your changes are in the pull request. Now I see in your pull request changes that we have done.

**Comment by samadsajanlal** [comment]
It might be easiest to do that as a separate pull request: I’ll close this one and make a new one with one commit in the next couple of hours.

**Comment by samadsajanlal** [comment]
@martinboehm I've created a new PR (#79) as a single commit.
As far as the backend service issues you faced, I tested this with Litecoin as well - building a backend for it, and it did not install a systemd service.

```
root@blockbook:~/go/src/blockbook# make deb-backend-litecoin
docker run -t --rm -e PACKAGER=0:0 -e UPDATE_VENDOR=1 -v /root/go/src/blockbook:/src -v /root/go/src/blockbook/build:/out blockbook-build-deb /build/build-deb.sh backend litecoin 
Package files for litecoin generated to build/pkg-defs
dpkg-buildpackage: info: source package backend
dpkg-buildpackage: info: source version 0.16.3-satoshilabs-1
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Jakub Matys <jakub.matys@satoshilabs.com>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build backend
 debian/rules clean
dh clean --with=systemd
   dh_testdir
   dh_auto_clean
	make -j1 clean
make[1]: Entering directory '/build/build/pkg-defs/backend'
rm -rf backend
rm -f litecoin-0.16.3-x86_64-linux-gnu.tar.gz
rm -f checksum
make[1]: Leaving directory '/build/build/pkg-defs/backend'
   dh_clean
 dpkg-source -b backend
dpkg-source: warning: no source format specified in debian/source/format, see dpkg-source(1)
dpkg-source: info: using source format '1.0'
dpkg-source: warning: source directory 'backend' is not <sourcepackage>-<upstreamversion> 'backend-0.16.3-satoshilabs'
dpkg-source: info: building backend in backend_0.16.3-satoshilabs-1.tar.gz
dpkg-source: info: building backend in backend_0.16.3-satoshilabs-1.dsc
 debian/rules build
dh build --with=systemd
   dh_testdir
   dh_update_autotools_config
   dh_auto_configure
   dh_auto_build
	make -j1
make[1]: Entering directory '/build/build/pkg-defs/backend'
wget https://download.litecoin.org/litecoin-0.16.3/linux/litecoin-0.16.3-x86_64-linux-gnu.tar.gz
--2018-10-19 22:47:44--  https://download.litecoin.org/litecoin-0.16.3/linux/litecoin-0.16.3-x86_64-linux-gnu.tar.gz
Resolving download.litecoin.org (download.litecoin.org)... 104.27.5.55, 104.27.4.55
Connecting to download.litecoin.org (download.litecoin.org)|104.27.5.55|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 25775514 (25M) [application/octet-stream]
Saving to: 'litecoin-0.16.3-x86_64-linux-gnu.tar.gz'

litecoin-0.16.3-x86_64-linux-gnu.tar.gz          100%[=========================================================================================================>]  24.58M  17.2MB/s    in 1.4s    

2018-10-19 22:47:46 (17.2 MB/s) - 'litecoin-0.16.3-x86_64-linux-gnu.tar.gz' saved [25775514/25775514]

wget https://download.litecoin.org/litecoin-0.16.3/linux/litecoin-0.16.3-linux-signatures.asc -O checksum
--2018-10-19 22:47:46--  https://download.litecoin.org/litecoin-0.16.3/linux/litecoin-0.16.3-linux-signatures.asc
Resolving download.litecoin.org (download.litecoin.org)... 104.27.5.55, 104.27.4.55
Connecting to download.litecoin.org (download.litecoin.org)|104.27.5.55|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 951 [application/octet-stream]
Saving to: 'checksum'

checksum                                         100%[=========================================================================================================>]     951  --.-KB/s    in 0s      

2018-10-19 22:47:46 (9.93 MB/s) - 'checksum' saved [951/951]

gpg --verify checksum
gpg: Signature made Wed Sep 19 21:35:34 2018 UTC
gpg:                using RSA key FE3348877809386C
gpg: Good signature from "Adrian Gallagher <thrasher@addictionsoftware.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 59CA F0E9 6F23 F537 4794  5FD4 FE33 4887 7809 386C
sha256sum -c --ignore-missing checksum
litecoin-0.16.3-x86_64-linux-gnu.tar.gz: OK
sha256sum: WARNING: 14 lines are improperly formatted
mkdir backend
tar -C backend --strip 1 -xf litecoin-0.16.3-x86_64-linux-gnu.tar.gz
# generated from exclude_files
rm backend/bin/litecoin-qt
make[1]: Leaving directory '/build/build/pkg-defs/backend'
   dh_auto_test
   create-stamp debian/debhelper-build-stamp
 debian/rules binary
dh binary --with=systemd
   create-stamp debian/debhelper-build-stamp
   dh_testroot
   dh_prep
   dh_installdirs
   dh_auto_install
   dh_install
   dh_installdocs
   dh_installchangelogs
   dh_systemd_enable
   debian/rules override_dh_systemd_start
make[1]: Entering directory '/build/build/pkg-defs/backend'
dh_systemd_start --no-start
make[1]: Leaving directory '/build/build/pkg-defs/backend'
   dh_installlogrotate
   dh_perl
   dh_link
   dh_strip_nondeterminism
   dh_compress
   dh_fixperms
   debian/rules override_dh_strip
make[1]: Entering directory '/build/build/pkg-defs/backend'
dh_strip --no-automatic-dbgsym
make[1]: Leaving directory '/build/build/pkg-defs/backend'
   dh_makeshlibs
   dh_shlibdeps
   dh_installdeb
   dh_gencontrol
   dh_md5sums
   dh_builddeb
dpkg-deb: building package 'backend-litecoin' in '../backend-litecoin_0.16.3-satoshilabs-1_amd64.deb'.
 dpkg-genbuildinfo
 dpkg-genchanges  >../backend_0.16.3-satoshilabs-1_amd64.changes
dpkg-genchanges: info: including full source code in upload
 dpkg-source --after-build backend
dpkg-buildpackage: info: full upload; Debian-native package (full source is included)
root@blockbook:~/go/src/blockbook# ls /etc/systemd/system
cloud-final.service.wants  electrumx_GAME.service  graphical.target.wants   network-online.target.wants     sockets.target.wants  syslog.service
cloud-init.target.wants    final.target.wants      iscsi.service            open-vm-tools.service.requires  sshd.service          timers.target.wants
default.target.wants       getty.target.wants      multi-user.target.wants  paths.target.wants              sysinit.target.wants
root@blockbook:~/go/src/blockbook# systemctl start backend-litecoin.service
Failed to start backend-litecoin.service: Unit backend-litecoin.service not found.
root@blockbook:~/go/src/blockbook# 
```

**Comment by jakm** [comment]
@samadsajanlal `make deb-backend-litecoin` just build a package in *build* directory, you have to install it to get a service installed. I don't see it in your output

**Comment by samadsajanlal** [comment]
Hi,
I extracted both debian packages, and did not see anything that was significantly different enough to warrant a failure of starting on our side.

Then, I proceeded to install the gamecredits package that was built: backend-gamecredits_0.15.3-satoshilabs-1_amd64.deb

I used dpkg -i backend-gamecredits_0.15.3-satoshilabs-1_amd64.deb

```
root@blockbook:~/go/src/blockbook/build# ls
backend-gamecredits_0.15.3-satoshilabs-1_amd64.deb  backend-litecoin_0.16.3-satoshilabs-1_amd64.deb  blockchaincfg.json  docker  templates  tools
root@blockbook:~/go/src/blockbook/build# dpkg -i backend-gamecredits_0.15.3-satoshilabs-1_amd64.deb 
Selecting previously unselected package backend-gamecredits.
(Reading database ... 85874 files and directories currently installed.)
Preparing to unpack backend-gamecredits_0.15.3-satoshilabs-1_amd64.deb ...
Unpacking backend-gamecredits (0.15.3-satoshilabs-1) ...
Setting up backend-gamecredits (0.15.3-satoshilabs-1) ...
root@blockbook:~/go/src/blockbook/build# systemctl status backend-gamecredits
● backend-gamecredits.service - GameCredits backend daemon
   Loaded: loaded (/lib/systemd/system/backend-gamecredits.service; enabled; vendor preset: enabled)
   Active: inactive (dead)

Oct 20 20:32:14 blockbook systemd[1]: [/lib/systemd/system/backend-gamecredits.service:38] Unknown lvalue 'MemoryDenyWriteExecute' in section 'Service'
```
OK, it installed properly as a service and does show a small error relating to MemoryDenyWriteExecute, which is a systemd thing and possibly because i'm on ubuntu 16.04.

Then I started the service:
```
root@blockbook:~# systemctl start backend-gamecredits.service
root@blockbook:~# gamecredits-cli getblockchaininfo
{
  "chain": "main",
  "blocks": 0,
  "headers": 51999,
  "bestblockhash": "91ec5f25ee9a0ffa1af7d4da4db9a552228dd2dc77cdb15b738be4e1f55f30ee",
  "difficulty": 0.000244140625,
  "mediantime": 1392757140,
  "verificationprogress": 2.923291583526061e-07,
  "chainwork": "0000000000000000000000000000000000000000000000000000000000100010",
  "pruned": false,
  "softforks": [
    {
      "id": "bip34",
      "version": 2,
      "reject": {
        "status": false
      }
    }, 
    {
      "id": "bip66",
      "version": 3,
      "reject": {
        "status": false
      }
    }, 
    {
      "id": "bip65",
      "version": 4,
      "reject": {
        "status": false
      }
    }
  ],
  "bip9_softforks": {
    "csv": {
      "status": "defined",
      "startTime": 1531612800,
      "timeout": 1563062400,
      "since": 0
    },
    "segwit": {
      "status": "defined",
      "startTime": 1531612800,
      "timeout": 1563062400,
      "since": 0
    }
  }
}
root@blockbook:~# systemctl stop backend-gamecredits.service
```

All looks good there. Using journalctl, I got the following logs - includes some simple start/stop previous tests to ensure that it wasn't just a fluke:

```
root@blockbook:~/go/src/blockbook/build# journalctl -u backend-gamecredits -f
-- Logs begin at Fri 2018-10-19 14:18:47 UTC. --
Oct 20 20:32:14 blockbook systemd[1]: [/lib/systemd/system/backend-gamecredits.service:38] Unknown lvalue 'MemoryDenyWriteExecute' in section 'Service'
Oct 20 20:32:51 blockbook systemd[1]: Starting GameCredits backend daemon...
Oct 20 20:32:51 blockbook systemd[1]: backend-gamecredits.service: Failed to read PID from file /run/gamecredits/gamecredits.pid: Invalid argument
Oct 20 20:32:51 blockbook systemd[1]: Started GameCredits backend daemon.
Oct 20 20:33:22 blockbook systemd[1]: Stopping GameCredits backend daemon...
Oct 20 20:33:26 blockbook systemd[1]: Stopped GameCredits backend daemon.
Oct 20 20:34:34 blockbook systemd[1]: Starting GameCredits backend daemon...
Oct 20 20:34:34 blockbook systemd[1]: backend-gamecredits.service: PID file /run/gamecredits/gamecredits.pid not readable (yet?) after start: No such file or directory
Oct 20 20:34:34 blockbook systemd[1]: Started GameCredits backend daemon.
Oct 20 20:35:39 blockbook systemd[1]: Stopping GameCredits backend daemon...
Oct 20 20:35:39 blockbook systemd[1]: Stopped GameCredits backend daemon.
```

I can't seem to reproduce the issue that @martinboehm stated occurred on the dev server: "Hi, built the GameCredits backend package and installed it to our dev server. When I try to start it sudo systemctl start backend-gamecredits.service, it seems it is not running in the daemon mode and fails to start properly."

Could you retry on a different environment? My box is a relatively clean copy of blockbook, and since yours is a dev environment I suspect that could have some stale code in it which causes the difference in observation

**Pull request closed without merging**
