### PR TITLE
perf: add contract info cache for spam token/nft transactions

### PR DESCRIPTION
**Pull request by kaladinlight**
This change adds an in memory cache for contract info on a per transaction basis. The cache fixes a big performance issue when calling `getTransactionFromBchainTx` for spam token/nft transactions. Instead of trying to fetch contract info and failing for thousands of transfers, we can just cache the state of the contract info which should not change during that single transaction fetch (specifically for invalid contracts since they are never saved to the db).

Example transaction: https://polygonscan.com/tx/0xb5b2790f6f38d2a87c28f420515bfb7e6d8a4866e123525ce6285a3c09969bfe

### CODE REVIEW

**Comment by martinboehm** [comment]
Thank you, I am going to test it.

**Comment by martinboehm** [comment]
Looks good. Maybe we could do a small optimization in `getEthereumTokensTransfers`, slightly reorder it and add a condition so that it does not allocate the cache map if there are no tokens:
```
func (w *Worker) getEthereumTokensTransfers(transfers bchain.TokenTransfers, addresses map[string]struct{}) []TokenTransfer {
	tokens := make([]TokenTransfer, len(transfers))
	if len(transfers) > 0 {
		sort.Sort(transfers)
		contractCache := make(contractInfoCache)
		for i := range transfers {
	...
```
What do you think?

**Comment by kaladinlight** [comment]
> Looks good. Maybe we could do a small optimization in `getEthereumTokensTransfers`, slightly reorder it and add a condition so that it does not allocate the cache map if there are no tokens:
> 
> ```
> func (w *Worker) getEthereumTokensTransfers(transfers bchain.TokenTransfers, addresses map[string]struct{}) []TokenTransfer {
> 	tokens := make([]TokenTransfer, len(transfers))
> 	if len(transfers) > 0 {
> 		sort.Sort(transfers)
> 		contractCache := make(contractInfoCache)
> 		for i := range transfers {
> 	...
> ```
> 
> What do you think?

Looks good to me! https://github.com/trezor/blockbook/pull/994/commits/1bf88451b6432c287a01f716f96b884dade2221b

**Comment by martinboehm** [comment]
@kaladinlight while looking at the code a bit more, maybe I would modify it slightly more:
1. check if the contract is in the cache directly in the `getEthereumTokensTransfers`
2. if it is there, use it and do not set the cache value again (it is unnecessary, it is already there)
3. only if it is not in cache, call `getContractInfo` (without any caching) and set the cache afterwards

**Comment by kaladinlight** [comment]
@martinboehm that makes sense. I went back and forth a bit on where to add, but this looks cleaner as you suggested: https://github.com/trezor/blockbook/pull/994/commits/819ce3e00b67de1606940b5bc185ce0ffcd7c4c4

**Comment by martinboehm** [comment]
Thank you, you have done it exactly as I wanted 👍 
I hope you will not hate me :) but I just realized that we are not using the Valid flag at all. The cache could be directly `map[string]*bchain.ContractInfo`.

**Comment by kaladinlight** [comment]
> Thank you, you have done it exactly as I wanted 👍 I hope you will not hate me :) but I just realized that we are not using the Valid flag at all. The cache could be directly `map[string]*bchain.ContractInfo`.

This I was aware of, but chose to cache the full state in case that would be used in the future. If there is no plan or intention of using this ever I can remove. If that is the case, would it be worth updating the function sig of `getContractInfo` to be more explicit?

Let me know how you want me to proceed :)

**Comment by martinboehm** [comment]
I would keep the function sig of getContractInfo as it is but as the caching logic is local to `getEthereumTokensTransfers`, we can cache only what we really need.

**Comment by martinboehm** [comment]
Great, thank you! 👍

**Pull request merged**
