### PR TITLE
Fix decred's xpub decoding

### PR DESCRIPTION
**Pull request by dmigwi**
This PR fixes the extend public Key decoding  functionality that was returning an error before.

@dajohi This PR is still essential even if https://github.com/martinboehm/btcutil/pull/3 was merged.
It could even override that PR since implementation unique to decred's checksum hash generation is handled here fully.

### CODE REVIEW

**Comment by martinboehm** [comment]
How is this related to this PR: WIP: decred: set proper base58 hasher (blake256). #245? Could you please consolidate this to one PR?

**Comment by dmigwi** [comment]
PR #245 is being fixed so that I can work like this PR without needing new decred imports in this PR, but that requires additional modifications to martinboehm/btcutil which are not yet ready.

**Comment by martinboehm** [comment]
OK, please tell me when you are ready to merge the decred modifications and in which single PR as I don't have time to analyze what does each of your (decred) PR do.

**Comment by dmigwi** [comment]
@martinboehm You can now merge this PR instead of #245

**Pull request merged**
