### PR TITLE
add support for eCash

### PR DESCRIPTION
**Pull request by PiRK**
This PR adds support for eCash

### CODE REVIEW

**Comment by PiRK** [comment]
I need some help to figure out how to run integration tests.
I tried `make test-integration ARGS="-run=TestIntegration/ecash/"`, but it doesn't find the testdata added by my last commit. I think it is looking for the json files in the blockbook github repository rather than locally:

```
$ make test-integration ARGS="-run=TestIntegration/ecash/"
Image blockbook-build is up to date
docker run -t --rm -e PACKAGER=1000:1000 -v "/home/pierre/dev/blockbook:/src" --network="host" blockbook-build make test-integration ARGS="-run=TestIntegration/ecash/"
rm -rf /go/src/github.com/trezor/blockbook
mkdir -p /go/src/github.com/trezor
cp -r /src /go/src/github.com/trezor/blockbook
cd /go/src/github.com/trezor/blockbook && go mod download
cd /go/src/github.com/trezor/blockbook && go test -tags 'rocksdb_6_16 integration' `go list github.com/trezor/blockbook/tests/...` -run=TestIntegration/ecash/
ok  	github.com/trezor/blockbook/tests	0.046s [no tests to run]
?   	github.com/trezor/blockbook/tests/dbtestdata	[no test files]
?   	github.com/trezor/blockbook/tests/rpc	[no test files]
?   	github.com/trezor/blockbook/tests/sync	[no test files]

```

**Comment by wakiyamap** [comment]
Maybe it will help you.
https://github.com/trezor/blockbook/blob/eth_update/docs/testing.md#integration-tests

**Comment by PiRK** [comment]
OK I figured out how to connect the integration tests and how to run them. Now I need to figure out how to override `AmountDecimalPoint` in a class that inherits `BitcoinLikeParser` in Go . It is not as straightforward as I expected it (I know python and c++).

**Comment by PiRK** [comment]
I managed to fix the number of decimals and make all tests pass. This is ready for a review.

**Comment by Klakurka** [comment]
We were told to ping @martinboehm about this one.

**Comment by martinboehm** [comment]
Hi, the project is not buildable at this moment, with this error:
```
# github.com/trezor/blockbook/bchain/coins/ecash
bchain/coins/ecash/ecashrpc.go:32:2: cannot use s (type *ECashRPC) as type bchain.BlockChain in return argument:
	*ECashRPC does not implement bchain.BlockChain (wrong type for GetBlockRaw method)
		have GetBlockRaw(string) ([]byte, error)
		want GetBlockRaw(string) (string, error)
```
The problem is caused by this commit 93ea126123541ceb272a12b2f5dc793792b986a9, which slightly modified the `BaseChain` interface. Could you please fix the code so that it works with the change? Thank you and sorry for the troubles.

**Comment by PiRK** [comment]
I fixed it in commit https://github.com/trezor/blockbook/pull/731/commits/70c19eb16752a0fd71a3ef6cee706fdbfe7ed459 .

Unit tests and integration tests are passing, on my machine.

**Comment by martinboehm** [comment]
Thank you!

**Pull request merged**
