### PR TITLE
Bump Groestlcoin backend version to 2.17.2

### PR DESCRIPTION
**Pull request by gruve-p**

### CODE REVIEW

**Comment by martinboehm** [comment]
I cannot build the backend, it fails to verify the signature with error:
```
gpg --verify checksum
gpg: Signature made Thu Feb 21 12:45:55 2019 UTC
gpg:                using RSA key 287AE4CA1187C68C08B49CB2D11BD4F33F1DB499
gpg: Can't check signature: No public key
```
You have changed the `verification_type `to `gpg-sha256`, you have to add the signer's public key to trusted gpg-keys, located in the path `build/docker/deb/gpg-keys`.

**Comment by martinboehm** [comment]
It is still failing:
```
gpg --verify checksum
gpg: Signature made Thu Feb 21 20:30:45 2019 UTC
gpg:                using RSA key 287AE4CA1187C68C08B49CB2D11BD4F33F1DB499
gpg: Good signature from "jackielove4u <jackielove4u@hotmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 287A E4CA 1187 C68C 08B4  9CB2 D11B D4F3 3F1D B499
sha256sum -c --ignore-missing checksum
sha256sum: WARNING: 14 lines are improperly formatted
sha256sum: checksum: no file was verified
Makefile:4: recipe for target 'all' failed

```

**Comment by gruve-p** [comment]
Can you try again please? We uploaded a different formatted SHA256SUMS.asc now

**Comment by martinboehm** [comment]
I can build it now, however it does not run as `groestlcoind` is not extracted as executable:
```
(130) > $ ll /opt/coins/nodes/groestlcoin/bin/                                                                                                                                                                                                           Permissions Size User Date Modified Name
.rw-r--r--  2.1M root 21 Feb 13:09  groestlcoin-cli
.rw-r--r--  2.7M root 21 Feb 13:09  groestlcoin-tx
.rw-r--r--   10M root 21 Feb 13:09  groestlcoind
```                                                                                                                                                                                                                                                                                 
I would really prefer if you were testing your changes before submitting a PR.

**Comment by gruve-p** [comment]
Apologies.
We just tested it locally now.

**Pull request merged**
