### PR TITLE
add bitcoin-signet

### PR DESCRIPTION
**Pull request by wakiyamap**
Trezor-wallet probably doesn't support signet,
but I'll just pull requests for the code because some people might use it.
Working server: https://signet-explorer.wakiyamap.dev/

ref https://github.com/trezor/blockbook/issues/175

### CODE REVIEW

**Review by decryp2kanon — APPROVED** [review]

**Comment by wakiyamap** [comment]
P.S.
The problem if you want to merge.

1. The third network port number setting(19090 or 29030?)
2. Currently there are only flags for mainnet and testnet (only flag true or false)
3. Need to create a test

**Comment by wakiyamap** [comment]
```
$ make test-integration ARGS="-v -run=TestIntegration/bitcoin_signet=main"
Image blockbook-build is up to date
docker run -t --rm -e PACKAGER=0:0 -e UPDATE_VENDOR=1 -v "/home/wakiyamap/blockbook:/src" --network="host" blockbook-build make test-integration ARGS="-v -run=TestIntegration/bitcoin_signet=main"
rm -rf /go/src/github.com/trezor/blockbook
mkdir -p /go/src/github.com/trezor
cp -r /src /go/src/github.com/trezor/blockbook
make prepare-vendor
make[1]: Entering directory '/build'
Updating vendor
go: downloading github.com/golang/protobuf v1.3.2
go: downloading github.com/ethereum/go-ethereum v1.9.20
go: downloading github.com/pebbe/zmq4 v1.0.0
go: downloading github.com/prometheus/client_golang v1.1.0
go: downloading golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9
go: downloading github.com/pkg/errors v0.8.1
go: downloading github.com/tecbot/gorocksdb v0.0.0-20180907100951-214b6b7bc0f0
go: downloading github.com/gogo/protobuf v1.1.1
go: downloading github.com/prometheus/common v0.9.1
go: downloading github.com/schancel/cashaddr-converter v0.0.0-20180113210041-0a38f5822f79
go: downloading github.com/prometheus/procfs v0.0.10
go: downloading github.com/mr-tron/base58 v1.1.3
go: downloading golang.org/x/sys v0.0.0-20200323222414-85ca7c5b95cd
go: downloading github.com/btcsuite/btcd v0.20.1-beta
go: downloading github.com/aristanetworks/goarista v0.0.0-20200224203130-895b4c57c44d
make[1]: Leaving directory '/build'
cd /go/src/github.com/trezor/blockbook && packr clean && packr
cd /go/src/github.com/trezor/blockbook && go test -tags integration `go list github.com/trezor/blockbook/tests/...` -v -run=TestIntegration/bitcoin_signet=main
=== RUN   TestIntegration
=== RUN   TestIntegration/bitcoin_signet=main
=== RUN   TestIntegration/bitcoin_signet=main/rpc
=== RUN   TestIntegration/bitcoin_signet=main/rpc/GetBlock
=== RUN   TestIntegration/bitcoin_signet=main/rpc/GetBlockHash
=== RUN   TestIntegration/bitcoin_signet=main/rpc/GetTransaction
=== RUN   TestIntegration/bitcoin_signet=main/rpc/GetTransactionForMempool
=== RUN   TestIntegration/bitcoin_signet=main/rpc/MempoolSync
    TestIntegration/bitcoin_signet=main/rpc/MempoolSync: rpc.go:394: Skipping test, mempool is empty
=== RUN   TestIntegration/bitcoin_signet=main/rpc/EstimateSmartFee
=== RUN   TestIntegration/bitcoin_signet=main/rpc/EstimateFee
=== RUN   TestIntegration/bitcoin_signet=main/rpc/GetBestBlockHash
=== RUN   TestIntegration/bitcoin_signet=main/rpc/GetBestBlockHeight
=== RUN   TestIntegration/bitcoin_signet=main/rpc/GetBlockHeader
--- PASS: TestIntegration (0.02s)
    --- PASS: TestIntegration/bitcoin_signet=main (0.02s)
        --- PASS: TestIntegration/bitcoin_signet=main/rpc (0.01s)
            --- PASS: TestIntegration/bitcoin_signet=main/rpc/GetBlock (0.00s)
            --- PASS: TestIntegration/bitcoin_signet=main/rpc/GetBlockHash (0.00s)
            --- PASS: TestIntegration/bitcoin_signet=main/rpc/GetTransaction (0.00s)
            --- PASS: TestIntegration/bitcoin_signet=main/rpc/GetTransactionForMempool (0.00s)
            --- SKIP: TestIntegration/bitcoin_signet=main/rpc/MempoolSync (0.00s)
            --- PASS: TestIntegration/bitcoin_signet=main/rpc/EstimateSmartFee (0.00s)
            --- PASS: TestIntegration/bitcoin_signet=main/rpc/EstimateFee (0.00s)
            --- PASS: TestIntegration/bitcoin_signet=main/rpc/GetBestBlockHash (0.00s)
            --- PASS: TestIntegration/bitcoin_signet=main/rpc/GetBestBlockHeight (0.00s)
            --- PASS: TestIntegration/bitcoin_signet=main/rpc/GetBlockHeader (0.00s)
PASS
ok  	github.com/trezor/blockbook/tests	0.091s
?   	github.com/trezor/blockbook/tests/dbtestdata	[no test files]
?   	github.com/trezor/blockbook/tests/rpc	[no test files]
?   	github.com/trezor/blockbook/tests/sync	[no test files]
```

**Comment by wakiyamap** [comment]
@martinboehm Should I add the test to bitcoinparser_test.go?
TestPackTx and TestUnpackTx?

**Comment by wakiyamap** [comment]
```
$ make test
Image blockbook-build is up to date
docker run -t --rm -e PACKAGER=0:0 -e UPDATE_VENDOR=1 -v "/home/wakiyamap/blockbook:/src" --network="host" blockbook-build make test ARGS=""
rm -rf /go/src/github.com/trezor/blockbook
mkdir -p /go/src/github.com/trezor
cp -r /src /go/src/github.com/trezor/blockbook
make prepare-vendor
make[1]: Entering directory '/build'
Updating vendor
go: downloading github.com/pebbe/zmq4 v1.0.0
go: downloading github.com/ethereum/go-ethereum v1.9.20
go: downloading github.com/schancel/cashaddr-converter v0.0.0-20180113210041-0a38f5822f79
go: downloading github.com/gogo/protobuf v1.1.1
go: downloading golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9
go: downloading github.com/golang/protobuf v1.3.2
go: downloading github.com/prometheus/client_golang v1.1.0
go: downloading github.com/tecbot/gorocksdb v0.0.0-20180907100951-214b6b7bc0f0
go: downloading github.com/prometheus/common v0.9.1
go: downloading github.com/mr-tron/base58 v1.1.3
go: downloading github.com/prometheus/procfs v0.0.10
go: downloading github.com/pkg/errors v0.8.1
go: downloading golang.org/x/sys v0.0.0-20200323222414-85ca7c5b95cd
go: downloading github.com/btcsuite/btcd v0.20.1-beta
go: downloading github.com/aristanetworks/goarista v0.0.0-20200224203130-895b4c57c44d
make[1]: Leaving directory '/build'
cd /go/src/github.com/trezor/blockbook && packr clean && packr
cd /go/src/github.com/trezor/blockbook && go test -tags unittest `go list ./... | grep -vP '^github.com/trezor/blockbook/(contrib|tests)'` 
?   	github.com/trezor/blockbook	[no test files]
ok  	github.com/trezor/blockbook/api	0.043s
ok  	github.com/trezor/blockbook/bchain	0.008s
?   	github.com/trezor/blockbook/bchain/coins	[no test files]
ok  	github.com/trezor/blockbook/bchain/coins/bch	0.033s
ok  	github.com/trezor/blockbook/bchain/coins/bellcoin	0.044s
ok  	github.com/trezor/blockbook/bchain/coins/bitcore	0.030s
ok  	github.com/trezor/blockbook/bchain/coins/bitzeny	0.066s
ok  	github.com/trezor/blockbook/bchain/coins/btc	0.036s
ok  	github.com/trezor/blockbook/bchain/coins/btg	0.080s
?   	github.com/trezor/blockbook/bchain/coins/cpuchain	[no test files]
ok  	github.com/trezor/blockbook/bchain/coins/dash	0.052s
ok  	github.com/trezor/blockbook/bchain/coins/dcr	0.077s
ok  	github.com/trezor/blockbook/bchain/coins/deeponion	0.042s
ok  	github.com/trezor/blockbook/bchain/coins/digibyte	0.063s
ok  	github.com/trezor/blockbook/bchain/coins/divi	0.063s
ok  	github.com/trezor/blockbook/bchain/coins/dogecoin	0.062s
ok  	github.com/trezor/blockbook/bchain/coins/eth	0.084s
ok  	github.com/trezor/blockbook/bchain/coins/flo	0.034s
ok  	github.com/trezor/blockbook/bchain/coins/fujicoin	0.056s
ok  	github.com/trezor/blockbook/bchain/coins/gamecredits	0.046s
ok  	github.com/trezor/blockbook/bchain/coins/grs	0.040s
ok  	github.com/trezor/blockbook/bchain/coins/koto	0.093s
ok  	github.com/trezor/blockbook/bchain/coins/liquid	0.045s
ok  	github.com/trezor/blockbook/bchain/coins/litecoin	0.064s
ok  	github.com/trezor/blockbook/bchain/coins/monacoin	0.045s
ok  	github.com/trezor/blockbook/bchain/coins/monetaryunit	0.077s
ok  	github.com/trezor/blockbook/bchain/coins/myriad	0.071s
ok  	github.com/trezor/blockbook/bchain/coins/namecoin	0.068s
ok  	github.com/trezor/blockbook/bchain/coins/nuls	0.051s
ok  	github.com/trezor/blockbook/bchain/coins/omotenashicoin	0.066s
ok  	github.com/trezor/blockbook/bchain/coins/pivx	0.077s
ok  	github.com/trezor/blockbook/bchain/coins/polis	0.096s
ok  	github.com/trezor/blockbook/bchain/coins/qtum	0.075s
ok  	github.com/trezor/blockbook/bchain/coins/ravencoin	0.043s
ok  	github.com/trezor/blockbook/bchain/coins/ritocoin	0.064s
ok  	github.com/trezor/blockbook/bchain/coins/snowgem	0.040s
ok  	github.com/trezor/blockbook/bchain/coins/unobtanium	0.126s
?   	github.com/trezor/blockbook/bchain/coins/utils	[no test files]
ok  	github.com/trezor/blockbook/bchain/coins/vertcoin	0.041s
ok  	github.com/trezor/blockbook/bchain/coins/viacoin	0.033s
ok  	github.com/trezor/blockbook/bchain/coins/vipstarcoin	0.026s
ok  	github.com/trezor/blockbook/bchain/coins/xzc	0.035s
ok  	github.com/trezor/blockbook/bchain/coins/zec	0.023s
?   	github.com/trezor/blockbook/build/templates	[no test files]
?   	github.com/trezor/blockbook/build/tools	[no test files]
?   	github.com/trezor/blockbook/build/tools/trezor-common	[no test files]
ok  	github.com/trezor/blockbook/common	0.006s
ok  	github.com/trezor/blockbook/db	0.722s
ok  	github.com/trezor/blockbook/fiat	2.217s
ok  	github.com/trezor/blockbook/server	0.301s
```

**Comment by wakiyamap** [comment]
Please let me know if you have any problems with the test content.

**Comment by Zh5577** [comment]
> Trezor-wallet probably doesn't support signet,
> but I'll just pull requests for the code because some people might use it.
> Working server: https://signet-explorer.wakiyamap.dev/
> 
> ref https://github.com/trezor/blockbook/issues/175

**Pull request merged**
