### PR TITLE
Add VIA support (0.15.2)

### PR DESCRIPTION
**Pull request by marsmensch**
Re-based, squashed & updated @romanornr's  work in https://github.com/trezor/blockbook/pull/23 ti implement VIA 0.15.2 support in blockbook.

### CODE REVIEW

**Comment by martinboehm** [comment]
Thank you for your contribution. 

Before we can merge your PR, please do this:
1) the files in `contrib/backends` are not necessary anymore, remove them
2) add unit and rpc tests
3) do not modify files that are not specific to your coin

You can use [this PR](https://github.com/trezor/blockbook/pull/79/files) as a reference of what should be done.

**Comment by romanornr** [comment]
First of all thanks @marsmensch 

Second yes unit tests are missing: https://github.com/trezor/blockbook/blob/9b583a9387906f67c91e6f9e4b2f8e5519d2e0d0/bchain/coins/viacoin/viacoin_test.go

Also seems like I have to make this https://github.com/samadsajanlal/blockbook/blob/ed7a4c2f8024e2ca14600d4e869023b876dc54f9/tests/sync/testdata/gamecredits.json for potential forks/reorgs etc

**Comment by marsmensch** [comment]
@martinboehm Thanks for the feedback. I was looking for past pull requests, but that one is definitely better than the others (especially dash) i looked at. I
* started porting the tests, they do currently fail
* removed the `.gitignore`, `README.md` and `contrib/backends` changes
* i squashed my changes so far

@romanornr, still todo
* fix the testcase fails (probably a copy paste error related to a tx)
* add a viacoin.json

**Comment by martinboehm** [comment]
Closed due to inactivity

**Pull request closed without merging**
