### PR TITLE
Add Denarius (D)

### PR DESCRIPTION
**Pull request by carsenk**
Trying to add Denarius (D) again.

This is still a WIP and any help would be greatly appreciated. 

I am wondering if snap installs could be utilized with this at all since we have our latest release always published via snap (snap install denarius)...

I need to play around with and test the block parsing/indexing still.

### CODE REVIEW

**Comment by martinboehm** [comment]
Hi. Regarding snap, we would like to avoid additional dependency. Is it possible to install without snap?

**Comment by carsenk** [comment]
Hey @martinboehm Yes you can install it without Snap, but typically snap is the easiest and fastest way currently. Snap also keeps you auto updated directly from our master repository/compiles from it directly.

Ubuntu Binary: https://github.com/carsenk/denarius/releases/download/untagged-511aae42c7463e987981/denariusd-ubuntu.tar.gz

**Comment by martinboehm** [comment]
Please create the configuration without Snap, so that I can install and run the Denarius backend to test your PR. Nobody stops you to use Snap on your servers, of course.

**Comment by carsenk** [comment]
@martinboehm It is configured to download the tar.gz and extract it.

**Comment by martinboehm** [comment]
I tried to build your project, however the backend part failed with:
```
[ "$(sha256sum denariusd-ubuntu.tar.gz | cut -d ' ' -f 1)" = "869B9A8276434EEBCD40460DC3B269291980924901260A98927D45CCBCD1BC0B" ]
Makefile:4: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/build/build/pkg-defs/backend'
dh_auto_build: make -j1 returned exit code 2
debian/rules:6: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
Makefile:34: recipe for target 'deb-denarius' failed
make: *** [deb-denarius] Error 2
```
Also, I do not see any integration tests in the PR and please clean up the code a bit (no commented out functions).

**Comment by carsenk** [comment]
Yea I have no idea how you guys have that setup as far as extracting the binary etc. It shouldn't need to be compiled from a Makefile, it is a prebuilt binary...Was hoping someone could assist with this implementation.

**Comment by martinboehm** [comment]
We do not compile it from sources even though we are using makefile. If you check https://github.com/trezor/blockbook/blob/master/build/templates/backend/Makefile, you will see that it does (based on content of the config.json):
```
wget {{.Backend.BinaryURL}}
[ "$$(sha256sum ${ARCHIVE} | cut -d ' ' -f 1)" = "{{.Backend.VerificationSource}}" ]
mkdir backend
{{.Backend.ExtractCommand}} ${ARCHIVE}
...
```
In your case, it fails in the second command, the sha256 verification. The downloaded `denariusd-ubuntu.tar.gz` does match the expected sha256, specified in `verification_source`.

**Comment by buzzkillb** [comment]
What version of debian are you running?

**Comment by martinboehm** [comment]
On the server where we test the code is Debian 4.9

**Comment by martinboehm** [comment]
Closed due to inactivity

**Pull request closed without merging**
